ariga/atlas

schema/schemaspec/extension.go, schema/schemaspec/extension_test.go, schema/schemaspec/schemahcl/context_test.go, schema/schemaspec/schemahcl/hcl.go, schema/schemaspec/schemahcl/hcl_test.go
also fixing a big in schemaspec.Resource `Scan` where *Ref fields were not properly supported.
=> schema/schemaspec/schemahcl: support Marshal

sql/internal/specutil/convert.go
a bug existed in specutil.Index existed where the method would look for the referenced column literally instead of unpacking the table and column names from the ref address.
=> sql/internal/specutil: fix bug in Index method

doc/md/sql.md
Documenting the Atlas HCL resources for SQL resources. 
TODO: "virtual types" for string, binary, and other types.
=> doc/md: documenting atlas hcl for sql resources

schema/schemaspec/spec.go, schema/schemaspec/spec_test.go
prep work for supporting slices of literals in schemaspec (currently only *Ref is supported).
=> schema/schemaspec: bool attribute helpers

schema/schemaspec/extension.go, schema/schemaspec/schemahcl/hcl_test.go, sql/mysql/sqlspec_test.go
More work towards supporting primitive types in HCL lists. 
Next PR will include support for numeric types.
=> schema/schemaspec: support string and bool lists

cmd/atlas/mux.go, cmd/atlas/provider.go
- for now there isn't a schema flag.
- the deafult schema in postgres is public.
- fixed a small bug when parsing dsn.
=> cmd/atlas: connect postgres

sql/postgres/sqlspec.go
Note, apply still fails due to some wrong parsing logic in unmarshaling
=> sql/postgres: support marshaling array types in sqlspec

sql/mysql/convert.go, sql/mysql/diff.go, sql/mysql/migrate.go, sql/postgres/convert.go, sql/postgres/diff.go, sql/postgres/migrate.go, sql/sqlite/convert.go, sql/sqlite/migrate.go
Working on the virtual types cleanup, I found myself needing these methods without the context of an active driver.
=> sql/*: decoupling FormatType methods from driver

sql/sqlspec/types.go, sql/sqlspec/types_test.go
Needed a way to go from `schemaspec.Type` to something the driver can parse into a `schema.Type`.
=> sql/sqlspec: adding function to print Type as string

schema/schemaspec/schemahcl/context_test.go, schema/schemaspec/schemahcl/hcl.go, schema/schemaspec/schemahcl/opts.go
this is infra to support `TypeSpec`s that have attributes that aren't represented as "type arguments" (for example `unsigned` in integer types
=> schema/schemaspec/schemahcl: don't break on type attributes that aren't defined as type arguments in sql

schema/schemaspec/schemahcl/context_test.go, schema/schemaspec/schemahcl/hcl.go, schema/schemaspec/schemahcl/opts.go
Needed to support
```hcl
status = enum("on","off","unknown")
```
=> schema/schemaspec/schemahcl: support variadic type spec attributes

sql/internal/sqlx/diff.go, sql/mysql/diff_test.go, sql/schema/migrate.go, sql/schema/schema.go
Some parts I can export while I still work on migration.
=> sq/internal/sqlx: add support for realm-level diffing

sql/internal/specutil/types.go, sql/internal/specutil/types_test.go
On second thought, I don't want this API exported yet. I'm going to add a bunch of other related stuff and I'd like to use it for a while before committing to the API.
=> sql/internal: moving PrintType and tests to internal

schema/schemaspec/spec.go, sql/internal/specutil/types.go, sql/internal/specutil/types_test.go
Stacked on #297 
Adding a new container type for working with TypeSpecs. This is added to make the needed changes to mysql/postgres for type-safe type definitions in Atlas DDL.
=> sql/internal/specutil: adding TypeRegistry for TypeSpecs

schema/schemaspec/schemahcl/context_test.go, schema/schemaspec/schemahcl/hcl.go, schema/schemaspec/schemahcl/opts.go
for types with non required attributes, support both:
```hcl
type = int
// AND
type = int(10)
```
=> schema/schemaspec/schemahcl: support optional type attrs

sql/internal/specutil/types.go, sql/internal/specutil/types_test.go
this fixes a bug where a typespec has an optional (non-required) type attribute, and the resulting DDL representation was too verbose. For instance, in some dialects both `varchar` and `varchar(20)` are valid. In these cases the `size` attribute is optional. In these cases if the size was not specified it would be rendered as `varchar(0)`. 
This PR adds a fix where the right-most optional args that have the zero value are omitted. so default:
`varchar(0)` => `varchar`, `x(10,0)` => `x(10)`, `x(0,10)` => remains `x(0,10)`
=> sql/internal/specutil: support omitting right-most zero-value optional param

schema/schemaspec/schemahcl/opts.go, schema/schemaspec/spec.go, sql/internal/spectest/spectest.go, sql/internal/specutil/types.go, sql/internal/specutil/types_test.go, sql/mysql/sqlspec.go, sql/mysql/sqlspec_test.go, sql/postgres/sqlspec.go, sql/postgres/sqlspec_test.go
Adding a sanity test for all driver type registries and fixing some bugs along the way. 
postgres enum needs some more love, but ill do that separately.
=> sql/internal/specutil: sanity tests for all drivers

schema/schemaspec/schemahcl/context_test.go, schema/schemaspec/schemahcl/opts.go
bugfix: for types that have "optional" parameters, such as float on MySQL - ie in the DDL both float, float(10), and float(10,2) are legit, only `float` and `float(10,2)` were supported. this PR adds support for the partial invocation `float(10)`, to mimick the db DDL.
=> schema/schemaspec/schemahcl: support partial type arguments

cmd/action/internal/build/build.go, cmd/action/version.go, internal/integration/integration_test.go
```go run  -ldflags "-X ariga.io/atlas/cmd/action/internal/build.Version=v0.1.1 -X 'ariga.io/atlas/cmd/action/internal/build.Date=$(Date +'%Y-%m-%d')'" ./cmd/atlas version```
shows version, date of compilation and release notes (github link)
=> cmd/action: add version

internal/integration/sqlite_test.go, sql/mysql/inspect.go, sql/sqlite/diff.go, sql/sqlite/inspect.go, sql/sqlite/inspect_test.go, sql/sqlite/migrate.go
In SQLite, almost any value is valid for DEFAULT. Use https://www.sqlite.org/syntax/literal-value.html to distinguish literals from raw expressions.
=> sql/sqlite: support literal expressions

internal/integration/go.sum, internal/integration/mysql_test.go, internal/integration/postgres_test.go, internal/integration/sqlite_test.go, schema/schemaspec/extension.go, schema/schemaspec/schemahcl/context.go, schema/schemaspec/schemahcl/hcl.go, schema/schemaspec/schemahcl/opts.go, schema/schemaspec/spec.go, sql/internal/specutil/convert.go, sql/postgres/convert.go, sql/postgres/sqlspec.go, sql/sqlspec/sqlspec.go
sqlspec.Column Default attribute is now a `schemaspec.Value` that can contain either `LiteralValue` or `RawExpr`. 
This is currently integration-tested on MySQL and SQLite.
=> sql/sqlspec: better support default values

internal/integration/mysql_test.go, internal/integration/postgres_test.go, internal/integration/sqlite_test.go, sql/mysql/sqlspec.go, sql/mysql/sqlspec_test.go, sql/postgres/sqlspec.go, sql/postgres/sqlspec_test.go, sql/sqlite/sqlspec.go, sql/sqlite/sqlspec_test.go
As discussed with @a8m and @zeevmoney, adding in each driver helper methods:
```go
var (
hclState = schemahcl.New(schemahcl.WithTypes(TypeRegistry.Specs()))
// UnmarshalHCL unmarshals an Atlas HCL DDL document into v.
UnmarshalHCL = schemaspec.UnmarshalerFunc(func(bytes []byte, i interface{}) error {
return UnmarshalSpec(bytes, hclState, i)
})
// MarshalHCL marshals v into an Atlas HCL DDL document.
MarshalHCL = schemaspec.MarshalerFunc(func(v interface{}) ([]byte, error) {
return MarshalSpec(v, hclState)
})
)
```
This should greatly reduce the appearance of this lovely snippet:
```go
schemahcl.New(schemahcl.WithTypes(mysql.TypeRegistry.Specs()))
```
=> sql: add MarshalHCL and UnmarshalHCL helpers to all drivers

cmd/action/env.go, cmd/action/internal/update/update.go, cmd/atlas/main.go, doc/md/CLI/atlas.md, doc/md/CLI/atlas_env.md
add atlas env command.
The long help describes all the available env' parameters.
When activating the cmd it prints the env params (when set).
This design is similar to what Go CLI does.
=> cmd/action: document no update env param

sql/mysql/inspect.go, sql/mysql/inspect_test.go, sql/mysql/migrate.go, sql/mysql/migrate_test.go
In MySQL, there's a way (supported also by ent) to append additional options to the `CREATE TABLE` statement.
=> sql/mysql: create options

sql/mysql/convert.go, sql/mysql/migrate.go
Unsupported types should be rejected in MySQL, but should
not cause the migration process to fail/panic
=> sql/mysql: avoid panic on migrate failure

sql/mysql/diff.go, sql/mysql/diff_test.go, sql/mysql/migrate.go, sql/mysql/migrate_test.go
Dropping charset or collations is applied using ModifyAttr.
Please see code comments.
=> sql/mysql: allow dropping table attributes

sql/internal/specutil/convert.go, sql/mysql/sqlspec_test.go, sql/postgres/sqlspec_test.go, sql/schema/dsl.go, sql/schema/dsl_test.go
This PR adds support for adding comments to the HCL. Opposed to the previous implementation where there was an `Comment` field added the the `sqlspec` structs this is no longer the case since SQLite for example does not support comments.
The current implementation also makes sure that no `commen = ""` attributes are rendered to the marshaled HCL if there are no comments.
=> Add support for SQL comments

internal/integration/mysql_test.go, sql/mysql/inspect.go, sql/mysql/migrate.go, sql/mysql/migrate_test.go, sql/schema/dsl.go, sql/schema/dsl_test.go
- Reject CHARSET/COLLATE attributes for non-char columns on migration
- "Normalize" inspected JSON columns on MariaDB
- Add UnsetCollate and UnsetCharset
=> sql/mysql: reject CHARSET/COLLATE attributes for non-char columns on migrate

sql/internal/sqlx/diff.go, sql/mysql/diff_test.go, sql/mysql/migrate.go, sql/mysql/migrate_test.go, sql/postgres/diff_test.go, sql/sqlite/diff.go, sql/sqlite/diff_test.go, sql/sqlite/migrate.go
We can consider to add schema changes as ModifyCharset and ModifyCollation
in the future to avoid all the type assertion.
=> sql/mysql: support modifying schema charset and collation attributes

doc/website/src/css/custom.css
DESCRIPTION
icon position is wrongly placed.
The reason is that the build version adds a div that dosnt exist in the local dev env (navbar__logo).  see attachments 
build
local
=> doc/website: align the atlas icon in the docs

schema/schemaspec/extension.go, schema/schemaspec/spec.go, sql/internal/specutil/convert.go, sql/internal/specutil/spec.go, sql/mysql/sqlspec.go, sql/mysql/sqlspec_test.go, sql/postgres/sqlspec.go
This PR introdues first steps to enable referenced column types. This is needed for the postgres implementation of enums.
The goal is to support HCL like the following:
```hcl
schema "sch" {}
table "tbl" {
column "col" {
type = enum.my_enum
}
}
enum "my_enum" {
values = ["on", "off"]
}
```
The first approach was to change `sqlspec.Table.Colum` from `*schemaspec.Type` to `schemaspec.Value` but handling a `Value` required different handling on `sqlspec.Table.Column.Type` and `sqlspec.Table.Column.Default` and the current structure didn't allow for this.
The current approach is valid too and all the implementation details are hidden from the actual `schema.Schema` the atlas internals work with.
Please note, that implementation for converting between `sqlspec.Schema` and `schema.Schema` will …
=> atlas: preparations for referenced column types

sql/postgres/sqlspec.go, sql/postgres/sqlspec_test.go
This is the `Unmarshal` part of the postgres support for enums.
=> sql/postgres: unmarshal HCL enum

schema/schemaspec/schemahcl/hcl.go, sql/internal/specutil/convert.go, sql/postgres/sqlspec.go, sql/postgres/sqlspec_test.go
This is the `Marshal` part of the postgres support for enums.
=> sql/postgres: marshal HCL enum

doc/md/ddl/intro.md
- remove extraneous spaces
- add spacing around code fences to match code fence formatting
- update phrasing to make clearer
- capitalize acronym (e.g., `http` -> `HTTP`)
=> doc/md: fmt consistency and update phrasing

doc/md/ddl/sql.md
- add missing `Example` and `Properties` section to `Index`
- fix grammar
- make markdown formatting consistent
=>  doc/md: add headers, update phrasing, formatting

cmd/action/mux.go, cmd/action/mux_test.go
`lib/pq` supports parsing runtime parameters from the DSN. Allowing for
configuration of the schema to inspect or apply on using the
`search_path` parameter.
Closes: #457
=> cmd/action: Parse schema name in postgres dsn

sql/sqlite/inspect.go, sql/sqlite/inspect_test.go
Going to move the DESC attribute to shared schema in future diffs.
=> sql/sqlite: inspect index sort order

sql/internal/specutil/spec.go, sql/mysql/sqlspec.go, sql/mysql/sqlspec_test.go
This PR adds support for marshalling inspected `ON UPDATE` clauses in MySQL / Maria to HCL. The marshaled HCL has the following form: 
```hcl
column "tTimestamp" {
null      = false
type      = timestamp(3)
default   = sql("current_timestamp(3)")
on_update = sql("current_timestamp(3)")
}
```
Adresses #471
=> sql/mysql: support marshal on update expressions in HCL

internal/integration/mysql_test.go, sql/mysql/inspect.go, sql/mysql/inspect_test.go, sql/mysql/sqlspec.go, sql/mysql/sqlspec_test.go
This is the "reverse" part to #486, unmarshaling HCL like shown into Go Types.
=> sql/mysql: support unmarshal on update expressions in HCL

sql/internal/specutil/convert.go, sql/internal/specutil/convert_test.go
When creating a "valid" HCL schema, and running it through Unmarshal, everything works, but if I add another schema block, and the `table` block doesn't have reference to to the schema, it panics.
For example, before the fix this is valid and works
```HCL
schema "test" {
}
table "accounts" {
column "name" {
type = varchar(32)
}
primary_key {
columns = [table.accounts.column.name]
}
}
```
But this panics:
```HCL
schema "test" {
}
schema "test2" {
}
table "accounts" {
column "name" {
type = varchar(32)
}
primary_key {
columns = [table.accounts.column.name]
}
}
```
**This fix will also enforce the usage of `schema = ` attribute in the `table` block and make it more consistent on all cases.**
=> specutil/convert: fix panic on missing schema ref in table block

cmd/action/diff.go
Fixing a bug where users couldn't diff schemas of different names.
=> cmd/action: allow diffing schemas with different names

internal/integration/mysql_test.go, internal/integration/testdata/mysql/index-desc.txt, schema/schemaspec/extension.go, schema/schemaspec/extension_test.go, schema/schemaspec/schemahcl/hcl.go, sql/internal/specutil/convert.go, sql/mysql/sqlspec_test.go, sql/sqlspec/sqlspec.go
Also, added support for scanning and printing `string` and `bool` pointers. We can consider adding more types in the future if we'll see a need for this.  
testscript for PostgreSQL will be added in future PRs.
=> sql/sqlspec: support marshaling index key parts

sql/internal/specutil/convert.go, sql/postgres/migrate.go
1. index-spec does not support custom attributes atm.
2. return more meaningful error in case of un supported postgres features in HCL (IDENTITY attribute for columns).
=> sql/postgres: minor fixes for postgres before release

cmd/action/apply.go, cmd/action/diff.go, cmd/action/diff_test.go, cmd/action/env.go, cmd/action/inspect.go, cmd/action/mux.go, cmd/action/mux_test.go, cmd/action/provider.go, cmd/action/root.go, cmd/action/schema.go, cmd/action/version.go
This PR adds unit tests for the `schema diff` command. It changes some things that I would like to modify in other commands, cc @yonidavidson.
The `*cobra.Command` is created by a constructor where input flags are passed as arguments, such that it can be more easily tested and relies less on global variables (which I know are common in CLI apps in Go but I personally dislike).
=> cmd/action: add unit tests for diff command

cmd/action/apply.go, doc/md/cli.md, internal/integration/integration_test.go
Closes #519 
- Adds `--approve` boolean flag to `schema apply` command. Default: false. When true, applies schema changes to given DSN without prompting user for approval. Useful for CI environments
1. Please feel free to request any/all changes. I know nothing about Go standards, or about naming preferences within this project. I chose `--approve` instead of `--apply` because I felt like running `atlas schema apply --apply` would feel kind of strange, but I'm totally open to other naming options.
2. I built and tested this locally with a docker-compose setup. I've included my steps below in case it helps in eventually building out some community contributing guidelines.
<details>
Docker Compose config:
```yml
version: "3"
services:
go:
image: golang:1.18beta1-bullseye
volumes:
- …
```
=> Add "auto approve" flag to "schema apply" command

sql/mysql/inspect.go, sql/mysql/inspect_test.go, sql/postgres/inspect.go, sql/postgres/inspect_test.go, sql/schema/inspect.go, sql/sqlite/inspect.go, sql/sqlite/inspect_test.go
Users should use `schema.Inspect` instead. Note that you should not give this PR too much attention because most of the inspection code will be changed tomorrow in order to reduce the number of queries on the database.
=> sql: drop the InspectTable option

doc/md/contributing.md
mostly copied from https://github.com/ent/ent/blob/master/doc/md/writing-docs.md (as the author of that doc I'm skipping attribution in the source code).
=> doc/md: guidelines for contributing documentation

cmd/action/env.go
in prep for working on unit tests for atlas cmd with @elad-n I'm organizing this command a little.
=> cmd/action: env command constructor

sql/postgres/sqlspec.go, sql/postgres/sqlspec_test.go
Problem: when using Postgres driver, the `character_varying()` does not require a length attribute:
https://github.com/ariga/atlas/blob/ce25dd8f5ae3f594644e6bfb3414b1532bfa3d0b/sql/postgres/sqlspec.go#L338
...yet `varchar()` does:
https://github.com/ariga/atlas/blob/ce25dd8f5ae3f594644e6bfb3414b1532bfa3d0b/sql/postgres/sqlspec.go#L337
The [official PostgreSQL documentation](https://www.postgresql.org/docs/9.3/datatype-character.html) treats these two identically:
>The notations `varchar(n)` and `char(n)` are aliases for character `varying(n)` and `character(n)`, respectively.
Solution: allow `varchar()` to be specified without the length, similarly to `character_varying()`.
=> Postgres driver: don't require varchar length

internal/integration/testdata/mysql/index-type.txt, internal/integration/testdata/postgres/index-type.txt, schema/schemaspec/schemahcl/opts.go, sql/mysql/diff.go, sql/mysql/driver.go, sql/mysql/inspect.go, sql/mysql/migrate.go, sql/mysql/migrate_test.go, sql/mysql/sqlspec.go, sql/postgres/migrate.go, sql/postgres/sqlspec.go, sql/postgres/sqlspec_test.go
Also, renamed `index.using` to `index.type`.
=> sql/mysql: support index types

sql/migrate/migrate.go, sql/migrate/migrate_test.go
This PR adds `TemplateFormatter` which implements `Formatter` and uses `text/template.Template`s to define how migrations files are written.
A default formatter is given, that is compatible with [golang-migrate/migrate](https://github.com/golang-migrate/migrate).
=> sql/migrate: add template formatter

doc/md/ddl/sql.mdx, doc/md/getting-started/02-inspecting.mdx, internal/integration/testdata/mysql/column-add-drop.txt, internal/integration/testdata/mysql/column-bool.txt, internal/integration/testdata/mysql/foreign-key-add.txt, internal/integration/testdata/mysql/foreign-key-modify-action.txt, internal/integration/testdata/mysql/index-add-drop.txt, internal/integration/testdata/mysql/index-desc.txt, sql/mysql/sqlspec.go, sql/mysql/sqlspec_test.go
`collate` is shorter and also used by MySQL/PostgreSQL
=> sql/mysql: rename collation attribute to collate

sql/mysql/diff.go, sql/mysql/diff_test.go
- Support for comparing float/decimal default values.
- Skip display-width and zerofill attributes until they will be supported in hcl
=> sql/mysql: minor diff changes

sql/postgres/inspect.go
…cause "to_regclass" will always return null if a table has capital letters
=> sql/postgres: support capital tables

sql/migrate/migrate.go, sql/migrate/migrate_test.go
This is the first PR of several to add the `atlas migrate` commands.
=> sql/migrate: (BC) read from state from migration directory instead of an extra state reader

cmd/atlas/doc.tmpl, doc/md/cli/reference.md, doc/package-lock.json
Adds documentation for atlas serve command.
=> cmd/atlas: add atlas serve docs

sql/mysql/inspect.go, sql/postgres/inspect.go, sql/sqlite/inspect.go
=> Default value of string like field can be empty string `""` or `"null"`

sql/sqlite/inspect.go, sql/sqlite/inspect_test.go
In the near future, I should add support for parsing expression, because it does support
expressions with comma atm (e.g. f(c,d))
=> sql/sqlite: initial support for index expression scanning

.github/workflows/ci.yml, cmd/action/migrate.go, cmd/action/provider.go, internal/ci/ci.tmpl, internal/ci/main.go, internal/integration/docker-compose.yaml, internal/integration/go.sum, internal/integration/integration_test.go, internal/integration/mysql_test.go, internal/integration/postgres_test.go, internal/integration/script_test.go, internal/integration/sqlite_test.go, internal/integration/testdata/mysql/autoincrement.txt, internal/integration/testdata/mysql/column-add-drop.txt, internal/integration/testdata/mysql/column-bool.txt, internal/integration/testdata/mysql/column-time-precision-mysql.txt, internal/integration/testdata/mysql/foreign-key-add.txt, internal/integration/testdata/mysql/foreign-key-modify-action.txt, internal/integration/testdata/mysql/index-add-drop.txt, internal/integration/testdata/mysql/index-desc.txt, internal/integration/testdata/mysql/index-expr.txt, internal/integration/tidb_test.go
Integration tests are now run each in its own job.
I had to do some kind of "hacky" solution, so it working correctly in the CI by using an env var when running the test. This does not affect local running.
=> internal/integration: speed up test execution

cmd/action/migrate.go, cmd/action/migrate_test.go, doc/md/cli/reference.md, sql/migrate/migrate.go, sql/migrate/migrate_test.go
This PR adds the `atlas migrate hash` command that can be used to re-hash the migration directory. This is needed for when the user did any manual change to the migration directory to create a correct `atlas.sum` file.
=> cmd/action: add atlas migrate hash command to solve checksum mismatches

schema/schemaspec/extension.go, schema/schemaspec/schemahcl/hcl.go, schema/schemaspec/schemahcl/hcl_test.go, schema/schemaspec/spec.go
adding a "Qualifier" attribute to `schemaspec.Resource`. In HCL can be defined as:
```hcl
resource "qualifier" "name" {
}
```
This is done as infrastructure for HCL document supporting two tables with the same name (but in different schemas).
=> schema/schemaspec: adding qualifier label to blocks

schema/schemaspec/schemahcl/context.go, schema/schemaspec/schemahcl/context_test.go
Add support for references to qualified resources and their attrs:
```hcl
user "atlas" "cli" {
version = "v0.3.9"
}
v = user.atlas.cli.version
r = user.atlas.cli
```
=> schema/schemaspec: support refs for qualified resources

cmd/action/apply.go, cmd/action/docker.go, cmd/action/mux_test.go, doc/md/cli/dev.md, doc/md/cli/reference.md, doc/md/cli/url.mdx
1. Adds `--verbose` to `atlas schema apply` to increase output if using `--dev-url docker://...`
2. Document usage of `docker://...`
=> cmd/action: add --verbose flag to apply command and document docker driver

.github/workflows/ci.yml, cmd/action/migrations/atlas.sum, internal/ci/ci.tmpl, schema/schemaspec/schemahcl/hcl.go, schema/schemaspec/schemahcl/opts.go, sql/migrate/migrate.go, sql/migrate/migrate_test.go, sql/migrate/testdata/atlas.sum
This PR fixes one bug, where a raised error from `UnmarshalText()` was not propagated up and hardens the integrity of the file by taking the filename of the migrations into the hash as well.
=> sql/migrate: harden atlas.sum file integrity

internal/integration/mysql_test.go, internal/integration/postgres_test.go, internal/integration/tidb_test.go, sql/internal/specutil/types.go, sql/mysql/convert.go, sql/mysql/inspect_test.go, sql/mysql/sqlspec_test.go, sql/postgres/convert.go, sql/postgres/inspect.go, sql/postgres/inspect_test.go, sql/postgres/sqlspec.go, sql/postgres/sqlspec_test.go, sql/schema/dsl.go, sql/schema/dsl_test.go, sql/schema/schema.go
The zero value of int does not represent the default value of the precision field. In PostgreSQL, it's 6, and in MySQL is 0.
=> sql/schema: use pointer for time precision

cmd/action/mux.go, cmd/action/mux_test.go
DSN for Postgres with underscore (_) in the username causes an error: first path segment in URL cannot contain colon. 
Reason: the provider (postgres://) got stripped from the DSN which is then parsed as an URL. If the DSN contains username:password url.Parse either misinterpret the url (if the username contains only letters) or otherwise produces an error "first path segment in URL cannot contain colon".
=> sql/postgres: fixed invalid postgres DSN

sql/postgres/sqlspec.go, sql/postgres/sqlspec_test.go
When marshalling 2 or more columns that reference the same enum type the generated Atlas DDL document contains duplicate entries for this enum (one entry per column).
=> sql/postgres: marshal spec duplicate enum entries

schema/schemaspec/extension.go, schema/schemaspec/extension_test.go, schema/schemaspec/schemahcl/hcl_test.go
Needed in order to support input variables for schema names: 
```hcl
variable "tenant" {
type = string
}
schema "tenant" {
name = var.tenant
}
table "users" {
schema = schema.tenant
}
```
=> schema/schemaspec: support defining resource names as attr

sql/postgres/inspect.go, sql/postgres/inspect_test.go
I have an unique index like this:
```sql
create unique index if not exists u_entity_name on entity (
entity_type,
coalesce(parent_id,0),
name
);
```
which when inspected become like this:
```hcl
index "u_entity_name" {
unique = true
type   = BTREE
on {
expr = "COALESCE(parent_id, (0)::bigint)"
}
on {
expr = "COALESCE(parent_id, (0)::bigint)"
}
on {
expr = "COALESCE(parent_id, (0)::bigint)"
}
}
```
Expected:
```hcl
index "u_entity_name" {
unique = true
type   = BTREE
on {
column = column.entity_type
}
on {
expr = "COALESCE(parent_id, (0)::bigint)"
}
on {
column = column.name
}
}
```
Reason: incorrect index metadata query.
=> sql/postgres: fixed inspection of multicolumn indexes

cmd/action/inspect.go, cmd/action/mux.go, cmd/action/provider.go
I was not working for URLs such as: `mysql://u:p@:3306/mysql`.
Next week, I plan to continue the refactoring @hedwigz started.
=> cmd/action: correctly handle mysql schema name in url format

sql/internal/sqlx/sqlx.go, sql/mysql/migrate.go, sql/mysql/migrate_test.go, sql/postgres/migrate.go, sql/postgres/migrate_test.go, sql/schema/migrate.go, sql/sqlite/migrate.go, sql/sqlite/migrate_test.go
<strike>The only thing left is to support renaming indexes in SQLite, which requires recreation of the index. </strike>
=> sql: add support for renaming resources (tables, columns and indexes)

sql/schema/migrate.go, sql/schema/migrate_test.go
I'm not super enthusiastic about this API, but we should make users' life easier when working with changes.
=> sql/schema: add helper methods for working with changesets

schema/schemaspec/schemahcl/context.go, schema/schemaspec/schemahcl/context_test.go, schema/schemaspec/schemahcl/hcl.go, schema/schemaspec/schemahcl/opts.go
Changing direction a bit on the API for evaluating atlas DDL documents that contain input variable definitions.
=> schema/schemaspec/schemahcl: state eval with input vars

schema/schemaspec/extension.go, schema/schemaspec/extension_test.go, schema/schemaspec/schemahcl/hcl.go, schema/schemaspec/schemahcl/hcl_test.go, sql/internal/spectest/spectest.go
Fixes a bug in cases like:
```hcl
variable "tenant" {
type = string
default = "test"
}
schema "tenant" {
name = var.tenant
}
table "users" {
schema = schema.tenant
column "id" {
type = int
}
}
```
When provided an input var such as `tenant=rotemtam`, the value of the reference to `schema.tenant` was `$schema.tenant` instead of `$schema.rotemtam`
=> schema/schemaspec/schemahcl: patch references to blocks with variable names

sql/sqlclient/client.go
This is needed to create the Ent client for EntRevisions. Once Ent is based on the Atlas driver, it can be removed again.
=> sql/sqlclient: expose registered name

internal/integration/mysql_test.go, sql/mysql/inspect.go
This is an optimistic attempt at a fix for expressions/functions in schema. Feel free to correct and guide me towards a better solve. :)
The wrapping is somewhat redundant when we already have `sql()` but [going by the comments in code](https://github.com/ariga/atlas/blob/60c0ed8bff94979c621c3453426a46c3ad44ee46/sql/mysql/migrate.go#L676-L677), backwards compatibility has made the situation a little messy.
Fixes #795 
Note: Initially, MySQL looked like it was working fine without this change.
But if we tried to inspect -> drop database -> create. We ended up with string default instead of an expression.
=> sql/mysql: Attempt a fix for RawExpr cases

doc/md/terraform.md
It seems like the blog post was moved to a different URL.
=> doc/website: fix a link to the Terraform blog post

cmd/atlascmd/migrate/migrate.go, cmd/atlascmd/migrate/migrate_test.go, internal/integration/cockroach_test.go, internal/integration/integration_test.go, internal/integration/mysql_test.go, internal/integration/postgres_test.go, internal/integration/sqlite_test.go, internal/integration/tidb_test.go, sql/mysql/driver.go, sql/postgres/crdb.go, sql/postgres/driver.go, sql/sqlclient/client.go, sql/sqlclient/client_test.go, sql/sqlite/driver.go
Ent based schema revisions are stored in its own database schema (except SQLite). The responsibility for parsing and editing connection URLs lay at the drivers. Ent based revisions introduce a new interface for the drivers to implement in order to alter the originally given connection URL to connect to another schema to store revisions table in.
=> cmd/atlascmd/migrate: introduce SchemaChanger interface

cmd/atlascmd/migrate/migrate.go, internal/integration/integration_test.go, sql/migrate/migrate.go, sql/migrate/migrate_test.go
This PR refactors the migration execution into two methods instead of one.
1. Compute the pending migration files
2. Execute a migration file onto a database
The above changes are needed to be able to wrap the execution of a migration file in a transaction. Splitting this into the two above methods also enables concurrent migration of multi-tenancy setups and keep them in sync before executing a new migration file.
Wrapping a migration execution in a transaction is should be controlled by the consumer instead of the executor itself.
=> sql/migrate: refactor execution (in preparation for transactions)

sql/sqlclient/client.go
Background: A driver registers its `Open` on the `driver`, but the current logic does this only for the first called flavor. The change in this PR ensure the same data, regardless of the flavor used to open an Atlas driver.
=> sql/sqlclient: use shared driver instance for different flavors

cmd/atlasci/internal/ci/ci.go, cmd/atlasci/internal/ci/run.go, cmd/atlasci/internal/ci/run_test.go, cmd/atlascmd/migrate.go, sql/migrate/migrate.go, sql/migrate/migrate_test.go, sql/schema/schema.go, sql/sqlcheck/sqlcheck.go
The general idea is to wrap these analyzers with top-level
runner that can be configured with custom reporter/writer
and setup driver-specific configuration.
On the execution part, the runner should be responsible for
scanning (and parsing, soon) the SQL files in the migration
directory, create a pass (check context) for each new one and
execute the registered and desired analyzers on it.
The reporting should be environment-aware. e.g. GitHub PR,
local development (HCL, Ent, plain SQL, etc).
=> cmd/atlasci/internal/ci: add basic run structure

internal/integration/sqlite_test.go, sql/sqlite/migrate.go
This PR ensures that if in cases where the `sqlite_sequence` table does not exist, this error is not returned back to the caller. Since we add a statement to create an entry in the `sqlite_sequence` table only if there is a PK requiring it, the table will exist when applying the changes.
=> sql/sqlite: fix sequence primary key bug

sql/mysql/driver.go, sql/mysql/inspect.go, sql/mysql/inspect_test.go
Unfortunately, I'm using MySQL 5.1 which is not support comments on indexes.
The schema inspection for an older version of MySQL seems to be working with this PR.
I know MySQL 5.1 is too old to support. However, this PR will be helpful for unlucky people like me.
=> sql/mysql: can inspect indexes which are not support comment

cmd/atlascmd/migrate/migrate.go, sql/migrate/migrate.go, sql/sqlite/driver.go
This change is the first one in a series of PR's to gradually make the migration directory the source of truth for all migration related logic (scanning, formatting, reading state, ...)
In the future one migration directory will be configured for exactly one dialect, migration tool, etc.
=> sql/migrate: StateReader if Dir has precedence

cmd/atlas/internal/cmdapi/migrate.go, cmd/atlas/internal/cmdapi/migrate_test.go
The idea is to stay consistent with 'schema apply' and the project file (atlas.hcl)
=> cmd/atlas: change migrate apply --to flag to --url

doc/md/cli/reference.md
Current instructions won't install `atlas` in a usable form, and are more for using Atlas in other ways.
This PR updates the docs to use the `go install` command instead, along with specifying version information, which is more likely to achieve what users are expecting when following other links in the docs to this section.
=> doc/md: updating install from source instructions

cmd/atlas/go.mod, cmd/atlas/go.sum, cmd/atlas/internal/cmdapi/migrate.go
Adds `atlas migrate status` command to print information about the migration status of a connected database.
=> cmd/atlas/cmdapi: add migrate status command

cmd/atlas/internal/ci/ci.go, cmd/atlas/internal/cmdapi/migrate.go, cmd/atlas/internal/cmdapi/migrate_test.go, internal/integration/mysql_test.go, internal/integration/postgres_test.go, sql/migrate/migrate.go, sql/migrate/migrate_test.go, sql/mysql/driver.go, sql/postgres/driver.go, sql/sqlclient/client.go, sql/sqlite/driver.go
This is a most basic implementation, that will only accept taking a snapshot, if a database is clean.
The drivers handle this differently:
- MySQL will consider a clean state if in case of a schema bound connection there are not tables, and in realm-bound connection there are not schemas.
- Postgres will consider a connection schema-bound, if it is connected to any other schema than `public`, or if the connection string explicitly requested `public` to be the connected schema (by using `search_path`). In the former, the database is clean of there are not tables in public and no other schemas. In the latter only the tables in public are taken into account.
- SQLite is not allowed to have any tables.
=> sql/migrate: introduce Snapshoter interface

cmd/atlas/internal/cmdapi/migrate.go, cmd/atlas/internal/cmdapi/project.go, cmd/atlas/internal/cmdapi/project_test.go, cmd/atlas/internal/cmdapi/schema.go, doc/md/cli/projects.md, internal/integration/testdata/sqlite/cli-migrate-project-multifile.txt
adds support for lists of values in the `src` attr of a project file env block:
```hcl
env "src_list" {
url = "URL"
dev = "sqlite://test?mode=memory&_fk=1"
src = [
"./schema/1.hcl",
"./schema/2.hcl",
]
migration_dir {
url = "file://migrations"
format = atlas
}
}
```
=> cmd/atlas/internal/cmdapi: support multi file schemas in project files

doc/website/docusaurus.config.js
=> doc/website/blog: add all posts to side nav

cmd/atlas/internal/cmdapi/project.go, internal/integration/testdata/sqlite/cli-migrate-diff-minimal-env.txt, internal/integration/testdata/sqlite/cli-migrate-lint-minimal-env.txt
As pointed by @masseelch , some commands can live fine without the `url` attr defined in the env.
=> cmd/atlas/internal/cmdapi: url attr optional in env

doc/md/concepts/workflows.md, doc/website/sidebars.js
Much of the content adapted from @masseelch's great blog post on the ent blog:
https://entgo.io/blog/2022/03/14/announcing-versioned-migrations
=> doc/md/concepts: declarative vs versioned migrations

cmd/atlas/internal/cmdapi/migrate.go, cmd/atlas/internal/cmdapi/migrate_test.go, cmd/atlas/internal/migrate/migrate.go, doc/md/reference.md, internal/integration/integration_test.go, sql/migrate/dir.go, sql/migrate/dir_test.go, sql/migrate/migrate.go, sql/migrate/migrate_test.go, sql/migrate/testdata/baseline/1_v1.sql, sql/migrate/testdata/baseline/2_v2.sql, sql/migrate/testdata/baseline/3_baseline.sql, sql/migrate/testdata/baseline/4_initial.sql, sql/mysql/driver.go, sql/mysql/driver_test.go, sql/postgres/driver.go, sql/postgres/driver_test.go, sql/schema/dsl.go, sql/sqlite/driver.go, sql/sqlite/driver_test.go, sql/sqlite/migrate_test.go
`--from` and `--baseline` may look the same but they are not; this will be explained soon in the docs.
=> sql/migrate: allow setting --from and --baseline versions

sql/mysql/migrate.go, sql/mysql/migrate_test.go
Avoid getting parse error from MySQL; first column is required by the grammar
=> sql/mysql: report error in case table has no columns

cmd/atlas/internal/cmdapi/migrate.go, internal/integration/go.mod, internal/integration/postgres_test.go, internal/integration/script_test.go, internal/integration/testdata/mysql/cli-migrate-diff.txt, internal/integration/testdata/postgres/cli-migrate-diff.txt, sql/internal/sqlx/dev_test.go, sql/internal/sqlx/plan.go, sql/internal/sqlx/sqlx.go, sql/internal/sqlx/sqlx_test.go, sql/migrate/migrate.go, sql/migrate/migrate_test.go, sql/mysql/inspect.go, sql/mysql/migrate.go, sql/mysql/migrate_test.go, sql/mysql/tidb.go, sql/postgres/diff.go, sql/postgres/migrate.go, sql/postgres/migrate_test.go, sql/sqlite/migrate.go, sql/sqlite/migrate_test.go
This is almost done.
Changes to be made in this PR:
- Add tests for `migrate diff` in MySQL/PostgreSQL 
Changes to be added in the next PRs:
- Add additional validation on the driver side; disallow using this feature programmatically, when the Atlas schema is not scoped to 1 database schema.
- Accept additional flag to allow changing the schema.
- Add docs and examples for Ent and golang-migrate.
=> sql/migrate: skip adding table qualifiers when connection/work is scoped to a schema

cmd/atlas/internal/cmdapi/migrate.go, cmd/atlas/internal/cmdapi/migrate_test.go, sql/migrate/migrate.go, sql/migrate/migrate_test.go
Keep it simple
- Reduce the number of locks from 3 to 1; each lock opens and acquires a connection if it's not running inside a transaction.
- Both diff and apply should acquire one lock and it should be done by the caller and not be done as a side effect. e.g. setting `MaxConnection(X)` can cause the CLI to block.
- Also, moving it out from the executor allows us to use external locks similar to terraform (e.g. DynamoDB or Consul)
=> sql/migrate: remove locking from executor

internal/integration/mysql_test.go, internal/integration/postgres_test.go, sql/internal/specutil/convert.go, sql/internal/specutil/spec.go, sql/mysql/sqlspec_test.go, sql/postgres/sqlspec.go, sql/postgres/sqlspec_test.go
The last part is to handle qualified enums as well.
=> sql/internal/specutil: patch foreign-key qualified references

cmd/atlas/internal/cmdapi/migrate.go, cmd/atlas/internal/cmdapi/migrate_test.go, cmd/atlas/internal/migrate/ent/convert.tmpl, doc/md/reference.md, sql/migrate/migrate.go, sql/migrate/migrate_test.go
Next PR will add the possibility to rollback more than one file in a transaction and therefore we need to re-apply more than one file in that case.
=> sql/migrate: pending files are all files after the last fully applied one

sql/migrate/dir.go, sql/migrate/lex.go, sql/migrate/lex_test.go
Next PRs will add support for additional position information and implement the `-- nolint` directive.
=> sql/migrate: scan associated comments from files

cmd/atlas/internal/cmdapi/migrate.go, cmd/atlas/internal/cmdapi/migrate_test.go, cmd/atlas/internal/cmdapi/schema.go, cmd/atlas/internal/cmdapi/schema_test.go, doc/md/reference.md
As a safety guard this command requires the `--local-url` flag as well as a confirmation from the user, unless the `--auto-approve` flag is given.
=> cmd/atlas/internal/cmdapi: add migrate clean command

doc/md/versioned/apply.mdx, doc/md/versioned/diff.mdx, doc/md/versioned/lint.md
Some of the CLI commands are formatted like this: 
This PR addresses those to match the rest, which look like this:
This also enables copy pasting for "new generation" shells like fish (which happens to be the one I am using).
=> doc/md: keep shell commands in consistent formatting

cmd/atlas/internal/cmdapi/migrate.go, cmd/atlas/internal/migrate/migrate.go, doc/md/reference.md, internal/integration/cockroach_test.go, internal/integration/integration_test.go, internal/integration/mysql_test.go, internal/integration/postgres_test.go, internal/integration/script_test.go, internal/integration/sqlite_test.go, internal/integration/testdata/migrations/mysql/1_initial.sql, internal/integration/testdata/migrations/mysql/atlas.sum, internal/integration/testdata/migrations/postgres/1_initial.sql, internal/integration/testdata/migrations/postgres/atlas.sum, internal/integration/tidb_test.go
This PR changes the default location of the revision information table. The old behavior was to store the table in a separate schema called `atlas_schema_revisions`. Now, if the connection is bound to a schema (e.g. when working with Ent), the table will be stored in that schema, unless the `--revision-schema` flag is given.
To not destroy pre-existing projects, we require the flag to be present, if the connection is schema bound, no table exists in that schema but we can find one in the old default schema.
=> cmd/atlas/internal: change default behavior of revision table location

sql/mysql/driver.go, sql/mysql/driver_test.go
Should have been done in https://github.com/ariga/atlas/pull/1109, but that PR forgot to set the changed values on the URL.
=> sql/mysql: ensure parseTime is always set

cmd/atlas/internal/docker/docker.go, cmd/atlas/internal/docker/docker_test.go
We already ignore the `public` schema in clean checks.
=> cmd/atlas: do not drop public schema on pg

cmd/atlas/internal/cmdapi/migrate.go, cmd/atlas/internal/cmdapi/migrate_test.go, doc/md/reference.md, doc/md/versioned/new.mdx, internal/integration/testdata/mysql/cli-migrate-apply.txt, internal/integration/testdata/postgres/cli-migrate-apply.txt, internal/integration/testdata/postgres/cli-migrate-status.txt, internal/integration/testdata/sqlite/cli-migrate-apply.txt, internal/integration/testdata/sqlite/cli-migrate-project.txt
Flag is usually never present in normal commands and always present in the hash command. It has no value.
=> cmd/atlas/internal/cmdapi: remove force flag

doc/website/docusaurus.config.js
Changes: in docusaurus.config.js, added code to redirect all articles under knowledge center from their old links to new links
=> doc/website: Fix redirection for articles under "Guides"

cmd/atlas/doc.go, cmd/atlas/internal/cmdapi/migrate.go, cmd/atlas/internal/migrate/migrate.go, doc/md/reference.md, internal/integration/go.mod, internal/integration/go.sum, internal/integration/integration_test.go, internal/integration/testdata/sqlite/cli-migrate-set-revision.txt, internal/integration/testdata/sqlite/cli-migrate-set.txt, sql/migrate/dir.go, sql/migrate/migrate.go, sql/migrate/migrate_test.go
This PR introduces the `atlas migrate set-revision version` command.
It will manipulate the revision table such, that, with linear history in mind, we end up with all migration versions up-to and including the given version marked as applied.
**Example**
```
Migrations: 1, 2, 4, 5, 6
Revisions : 1, 2, 4
^
has an error
```
Running `atlas migrate set-revision 2` will result in:
```
Migrations: 1, 2, 4, 5, 6
Revisions : 1, 2
```
Running `atlas migrate set-revision 4` will result in:
```
Migrations: 1, 2, 4, 5, 6
Revisions : 1, 2, 4
```
Running `atlas migrate set-revision 7 --ignore-missing-migration ` will result in:
```
Migrations: 1, 2, 4, 5, 6
Revisions : 1, 2, 4, 5, 6, 7
```
Running `atlas migrate set-revision 3 --ignore-missing-migration && atlas migrate set-revision 6` will result in: …
=> cmd/atlas/internal/cmdapi: add atlas migrate set-revision

cmd/atlas/internal/cmdapi/migrate.go, cmd/atlas/internal/cmdapi/migrate_test.go, cmd/atlas/internal/cmdapi/schema_test.go, doc/md/guides/migration-tools/golang-migrate.md, doc/md/reference.md, doc/md/versioned/diff.mdx, doc/md/versioned/import.mdx, internal/integration/testdata/mysql/cli-migrate-diff-format.txt, sql/migrate/migrate_test.go
Migration directory format is now given by a query parameter, e.g. `file://migrations?format=atlas`. Some tests have not been changed to the new behavior since the flag is still working for BC reasons.
Encoding all meta into the query string increases API consistency and also adds the possibility to add more meta without adding more and more flags. E.g. replaying until a specific version could be done by `file://migrations?format=atlas&version=1234`.
=> cmd/atlas/internal/cmdapi: add format query parameter to migration dir URL

cmd/atlas/internal/cmdapi/cmdapi.go, cmd/atlas/internal/cmdapi/diff.go, cmd/atlas/internal/cmdapi/diff_test.go, cmd/atlas/internal/cmdapi/migrate.go, doc/md/reference.md
This is the first PR in a series of PRs to enable all schema and migrate commands to work with `migrate.StateReader` to enable the CLI to read and diff states between every supported state definitions (currently HCL, migration directory and database connection).
As a second goal the PR's aim to increase the amount of code shared between `schema` and  `migrate` commands and refactor the code structure to increase readability and reduce global state (which is incredibly painful when unit testing).
=> cmd/atlas/internal/cmdapi: schema diff works with statereaders

cmd/atlas/internal/cmdapi/migrate.go
According to this [guide](https://atlasgo.io/atlas-schema/projects#projects-with-versioned-migrations), `dir` can be set from a project file, but it seems not to work.
=> cmd/atlas/internal/cmdapi/migrate: set dir value from env in migrate command

sql/internal/specutil/convert.go, sql/mysql/sqlspec_test.go
Also, in case of columns-only (not expression) indexes. For example, index a column prefix
=> sql/internal/specutil: add index-part attributes to spec

internal/integration/docker-compose.yaml
Avoid name conflicts, e.g. if working locally on Ent as well
=> internal/integration: name docker containers

internal/integration/testdata/mysql/cli-migrate-apply.txt, sql/sqlclient/client.go
DSN contains the credential for connection to the database, should not print to the JSON log
=> sql/sqlclient: remove DSN from the JSON output

sql/spanner/inspect.go, sql/spanner/inspect_test.go
Changes queries to utilize ordinal parameters instead of named params w/ unnest.
=> sql/spanner: Alter querySchema to use str interpolated params

internal/integration/spanner_test.go, sql/spanner/migrate.go
sql/spanner was missing a call to `sqlx.DetachCycles` which performs a topological sort of the changes to order them correctly.
=> sql/spanner: fix change ordering

.github/workflows/ci.yml, internal/ci/main.go, sql/spanner/sqlspec.go
This adds a minimal implementation of parsing and diffing to close the HCL->SQL loop.
=> sql/spanner: Add initial parsing and diffing implementations

sql/postgres/inspect.go, sql/postgres/inspect_test.go, sql/postgres/sqlspec.go
Will be used by Ent index annnotations
=> sql/postgres: expose UnmarshalText for parsing operator classes

internal/integration/spanner_test.go, sql/spanner/convert.go, sql/spanner/inspect.go
This adds initial ARRAY type support to the spanner driver.
=> sql/spanner: Add initial ARRAY type handling

go.mod
Running under `1.18` causes the following error:
```
internal/cmdapi/vercheck/vercheck.go:72:23: undefined: url.JoinPath
```
=> Bumps Go version to 1.19 due to url.JoinPath

cmd/atlas/internal/cmdapi/cmdapi.go, cmd/atlas/internal/cmdapi/migrate.go, cmd/atlas/internal/cmdapi/schema.go, cmd/atlas/internal/cmdapi/schema_test.go, internal/integration/go.mod
Next PR, will add support for logging and test it on MySQL/PostgreSQL using testscript.
=> cmd/atlas: add support for multi-env in declarative workflow

cmd/atlas/go.work.sum
The sumfile line for the newer version of sqlite isn't in this file which is breaking CI for me.
This is the result of running `go run main.go migrate apply --dir file://internal/cmdapi/testdata/sqlite --url sqlite://db?_fk=1` locally.
=> cmd/atlas: Update go.work.sum

cmd/atlas/internal/cmdapi/migrate.go, cmd/atlas/internal/cmdapi/project.go, cmd/atlas/internal/cmdlog/cmdlog.go
From:
To:
The `exit status 1` comes from `go run`. Ignore it.
=> cmd/atlas: avoid logging errors twice

internal/integration/spanner_test.go, sql/spanner/inspect.go
This adds the TestSpanner_Sanity integration test which is meant to cover all reasonable column types to show that inspection is producing the expected output.
=> spanner: Add Sanity integration test

cmd/atlas/internal/cmdapi/migrate.go, doc/md/reference.md
`atlas migrate diff -u` does not make sense.
=> cmd/atlas: remove short form for --to flag

cmd/atlas/internal/docker/docker.go, cmd/atlas/internal/docker/docker_test.go
Also, using 'docker kill' sends SIGKILL and not SIGTERM results faster teardown
=> cmd/atlas/docker: use mysql/mariadb images that boot up faster

sql/postgres/migrate.go, sql/postgres/migrate_test.go
That is because the 'public' schema is automatically created by PostgreSQL in every new database, and running the command with this clause will fail in case the schema already exists.
See: https://discord.com/channels/930720389120794674/1017364262097784892/1059913355504128070
=> sql/postgres: always create 'public' schemas with IF NOT EXISTS clause

doc/website/docusaurus.config.js, sql/sqlclient/client.go, sql/sqlclient/client_test.go
Replaced this error: `Error: sql/sqlclient: no opener was registered with name ""` with a helpful one.
=> sql/sqlclient: improve url/opener error

sql/postgres/migrate.go, sql/postgres/migrate_test.go
i.e., restore function used by Snapshoter
=> sql/postgres: clear enum types after replaying migrations directory

sql/mysql/migrate.go, sql/mysql/migrate_test.go
In case the PK is attach to an AUTO_INCREMENT column, separating it into two commands may cause constraint violation
=> sql/mysql: DROP and ADD primary key on the same command

cmd/atlas/go.mod, cmd/atlas/go.sum, cmd/atlas/go.work.sum, cmd/atlas/internal/cmdapi/migrate.go, cmd/atlas/internal/cmdapi/migrate_test.go, cmd/atlas/internal/lint/lint_test.go, internal/integration/go.mod, internal/integration/go.sum, internal/integration/mysql_test.go, internal/integration/postgres_test.go, sql/migrate/migrate.go, sql/migrate/migrate_test.go, sql/mysql/driver.go, sql/postgres/driver.go, sql/sqlite/driver.go
Atlas wasn't working for my existing sqlite database.
According to tutorial from https://entgo.io/docs/versioned/upgrade-prod
following error shoud have occured:
```console
Error: sql/migrate: connected database is not clean: found table "atlas_schema_revisions" in schema "db". baseline version or allow-dirty is required
```
but that didn't happen, I saw this one instead:
```console
Error: sql/migrate: connected database is not clean: found multiple tables: 15
```
Googling didn't help, also I couldn't find any issues on github that were mentioning this.
Weird. Time to investigate!
The root of problem showed itself quite promptly in sql/migrate/migrate.go on line 539, `errors.As` was not able match error.
----
Some functions were returning `migrate.NotCleanError` value, some others - …
=> sql/migrate: ensure consistency of NotCleanError

internal/integration/hclsqlspec/hclsqlspec_test.go, schemahcl/context_test.go, schemahcl/hcl.go, schemahcl/opts.go, schemahcl/stdlib.go, sql/mysql/sqlspec.go, sql/postgres/sqlspec.go, sql/postgres/sqlspec_test.go, sql/sqlite/sqlspec.go
Limiting the variable's scope to specific attributes provides type-safety to the schema. i.e., Eval fails on "parsing" and not on the decoding stage, which improves the error reporting. 
From:
```
Error: schemahcl: failed reading spec as *postgres.doc: set field "type": converting cty.Value to *schemahcl.Type: incorrect type type
```
To:
```
Error: schema1.hcl:6,12-18: Unknown column.type; There is no type named "string".
```
=> schemahcl: limit type variables scope to specific location

cmd/atlas/internal/cmdapi/cmdapi.go, cmd/atlas/internal/cmdapi/migrate.go, cmd/atlas/internal/cmdapi/migrate_test.go, cmd/atlas/internal/cmdapi/project.go, cmd/atlas/internal/cmdapi/schema.go, cmd/atlas/internal/cmdapi/schema_test.go, cmd/atlas/internal/cmdlog/cmdlog.go, cmd/atlas/internal/cmdlog/cmdlog_test.go, doc/md/atlas-schema/projects.mdx, doc/md/declarative/diff.mdx, doc/md/reference.md, doc/md/versioned/diff.mdx, doc/website/package-lock.json, internal/integration/postgres_test.go, internal/integration/testdata/mysql/cli-migrate-diff.txt, internal/integration/testdata/postgres/cli-migrate-diff.txt, internal/integration/testdata/sqlite/cli-migrate-diff-minimal-env.txt, internal/integration/testdata/sqlite/cli-migrate-diff-multifile.txt, internal/integration/testdata/sqlite/cli-migrate-diff.txt, internal/integration/testdata/sqlite/cli-migrate-lint-modify-nullability.txt, internal/integration/testdata/sqlite/cli-migrate-project-multifile.txt, internal/integration/testdata/sqlite/cli-migrate-project.txt, sql/migrate/dir.go, sql/migrate/migrate.go
Add support for `--format` in both `migrate diff` and `schema diff` commands. Note that since indentation config is required on planning time (and not when writing the `migrate.Plan`), the `migrate diff` command fakes the execution of the `sql` template function (see `mayIndent`). This behavior has some limitations, but I doubt users will encounter them.
=> cmd/atlas: add --format to both schema and migrate diff

sql/postgres/migrate.go, sql/postgres/migrate_test.go
Reusing the dev-database (from both loading and diff), will cause the enum to not be created on diff. Fixed https://github.com/ariga/atlas/issues/1503.
=> sql/postgres: clean enums on table drop

sql/postgres/driver.go, sql/postgres/inspect.go, sql/postgres/migrate.go, sql/postgres/migrate_test.go
In case other resources like views were created in the migration, replay will fail
=> sql/postgres: drop tables with CASCADE on cleanup

sql/internal/specutil/convert.go
=> make a string lower before doing the string comparison

sql/postgres/inspect.go, sql/postgres/migrate.go, sql/postgres/migrate_test.go, sql/schema/migrate.go
The `Concurrently` option only affects how the index is created and doesn't provide any information about the index itself. 
cc @ivanvanderbyl
=> sql/postgres: change the Concurrently attribute to a schema.Clause

cmd/atlas/internal/sqlparse/pgparse/pgparse.go, cmd/atlas/internal/sqlparse/pgparse/pgparse_test.go, internal/integration/testdata/postgres/cli-migrate-lint-concurrent-idx.txt, sql/postgres/postgrescheck/postgrescheck.go, sql/postgres/postgrescheck/postgrescheck_test.go
An analyzer that detects two cases:
1. Missing the `CONCURRENTLY` option in `CREATE INDEX`/`DROP INDEX` commands and report accordingly. Error (red CI) if was set this way. Note the code skips tables that were created in the same file.
2. Warning about missing `atlas:txmode none` directive in case the migration file contains concurrent commands (invalid operation).
Future improvements: As concurrent creation and deletion operations cannot run within a transaction, it is recommended that users remove unrelated statements (such as `ALTER TABLE`) from the file. This is because other commands can, and should, be executed within a transaction.
=> sql/postgres/postgrescheck: add concurrent index commands analyzer

cmd/atlas/internal/cmdapi/schema.go, cmd/atlas/internal/cmdapi/schema_test.go, doc/md/reference.md, internal/integration/testdata/mysql/cli-inspect-file.txt, internal/integration/testdata/postgres/cli-inspect-file.txt, internal/integration/testdata/postgres/cli-inspect.txt, internal/integration/testdata/postgres/cli-migrate-apply.txt, internal/integration/testdata/sqlite/cli-inspect.txt, internal/integration/testdata/sqlite/cli-migrate-apply.txt
This PR updates the `atlas schema inspect` command to support other resources: sql-file, hcl-file, and Ent's schema. When you do inspect those resources, you need to provide a dev-DB for Atlas to replay changes on it.
With an unexpected side effect, to fix what we believe to be a bug with the inspect command. The `--exclude` flag when used with schema connection can only exclude sub-resources such as: table, column, index, ... and no longer exclude the current schema.
Those commands are invalid
```shell
atlas schema inspect -u "mysql://user:pass@localhost:3306/dbname" --exclude=dbname
atlas schema inspect -u "mysql://user:pass@localhost:3306/dbname" --exclude=dbname.*
atlas schema inspect -u "mysql://user:pass@localhost:3306/dbname" --exclude=dbname.table1
```
Need to update to this: …
=> schema/inspect: support inspect for non-database resource

cmd/atlas/internal/cmdapi/migrate.go, cmd/atlas/internal/cmdapi/migrate_test.go
Also disable printing usage on non-input validation
=> cmd/atlas: report tx creation failures

cmd/atlas/internal/cmdext/cmdext.go, doc/md/concepts/url.mdx
=> cmd/atlas/internal/cmdext: use dev-database schema in ent loader as default schema

sql/sqltool/tool.go, sql/sqltool/tool_test.go
Invalid order migration files when sorting with filename
```
V1__.sql
V1.7__.sql
```
after sort
```
V1.7__.sql
V1__.sql
```
=> sql/sqltool: fix flyway invalid order migrations

cmd/atlas/internal/cmdapi/migrate_test.go
fixes https://github.com/ariga/atlas/issues/1709
=> chore: Use ldflag version in migrate_test.go in NoPendingFiles

cmd/atlas/internal/cmdext/reader.go, internal/integration/testdata/postgres/cli-migrate-diff-unsupported.txt
Also fixed https://github.com/ariga/atlas/issues/1732
=> cmd/atlas: defer HCL normalization until ReadState is called

sql/mssql/driver.go, sql/mssql/inspect.go, sql/mssql/inspect_test.go
- sql/mssql: inspect computed column
=> sql/mssql: inspect computed column

schemahcl/types.go, sql/internal/spectest/spectest.go
I encountered  nil pointer deference panic when using `mysql.EvalHCLBytes` func,
see  relevant stack trace part.
=> schemahcl: fix panic in Type method

schemahcl/context.go, schemahcl/context_test.go
This helps catching invalid statements before executing them on dev-database
=> schemahcl: allow reference blocks in template expressions 

cmd/atlas/internal/sqlparse/pgparse/pgparse.go, cmd/atlas/internal/sqlparse/pgparse/pgparse_test.go
Fixed https://github.com/ariga/atlas/issues/1851
=> cmd/atlas: support for quoted identifiers in concurrent index creation

cmd/atlas/internal/cmdapi/schema.go, cmd/atlas/internal/cmdlog/cmdlog.go, cmd/atlas/internal/cmdlog/cmdlog_test.go
Printing errors in templates do not return exit code 1.
=> cmd/atlas: do not pass error to inspect template

cmd/atlas/internal/cmdapi/vercheck/vercheck.go, cmd/atlas/internal/cmdapi/vercheck/vercheck_test.go
I've changed the file mode passed to `os.WriteFile` from 0777 to 0666.
That is, I've removed the executable bits, which are unnecessary and may lead to undesirable consequences.
=> Remove executable bits in `os.WriteFile`

sql/internal/sqlx/sqlx.go, sql/internal/sqlx/sqlx_test.go, sql/mysql/inspect.go, sql/mysql/inspect_test.go, sql/sqlite/diff.go, sql/sqlite/inspect.go
Note, as of MySQL 8.0.17, the ZEROFILL attribute is deprecated and expected to be removed in future versions.
Fixed https://github.com/ariga/atlas/issues/1937
=> sql/mysql: respect zerofill attribute in float/double types

cmd/atlas/internal/cmdapi/migrate.go, doc/md/reference.md, sql/migrate/dir.go, sql/migrate/dir_test.go, sql/migrate/migrate.go, sql/migrate/migrate_test.go
This is currently a work in progress and should not be used until the documentation will be updated with this info.
=> sql/migrate: add support for baseline/tags files 

internal/integration/postgres_test.go, sql/internal/sqlx/sqlx.go
=> sql/internal/sqlx: support cross-schema refs with same names

doc/md/getting-started/getting-started.mdx
This PR fixes a small typo in the EULA url in the getting-started page.
=> doc/md: fix small typo in eula url

cmd/atlas/internal/cmdapi/migrate.go, doc/md/reference.md
It was not used by this command
=> cmd/atlas: remove revision-schema flag from migrate diff

doc/md/guides/orms/gorm.md
https://atlasgo.io/guides/orms/gorm has the following sample code:
```go
func main() {
stmts, err := gormschema.New("mysql", &models.User{}, &models.Pet{}).Load()
if err != nil {
fmt.Fprintf(os.Stderr, "failed to load gorm schema: %v\n", err)
os.Exit(1)
}
io.WriteString(os.Stdout, stmts)
}
```
However, the syntax for `gormschema.New` only takes `String` as argument and the provided code would not compile.
Changed sample code contents to match https://github.com/ariga/atlas-provider-gorm README
=> doc/md: fixed wrong sample code for gorm guide

.github/workflows/cd-docker-push-mysql_oss.yaml
Closes #1997 
This PR builds `arm64` Docker images for mysql and mariadb, excluding the mysql image versions that don't have an upstream arm64 base image.
=> Build arm64 mysql and mariadb Docker images

.github/ops/mysql/Dockerfile, .github/workflows/cd-docker-push-mysql_oss.yaml
Followup from #1998, this fixes two issues with the current workflow:
1. The workflow filename has changed, so builds aren't triggered on merge anymore
2. The `mariadb:latest` image does not have `mysqld`, so this adds a new build arg to override to `mariadbd` for that image build. This unblocks the regular cron builds.
=> .github/ops/mysql: fix Dockerfile builds, fix mariadb:latest

.github/ops/mysql/Dockerfile, .github/workflows/cd-docker-push-mysql_oss.yaml
Third time's the charm maybe 🙂 
Followup to #2001, this fixes two more issues:
1. Pre-create the `initialized-db` dir with the correct user
2. Don't fail all builds if a single one fails
cc @giautm
=> Don't fail all Docker image builds on single failure, pre-create initialized-db

.github/ops/mysql/Dockerfile
Followup to #2003.
I was able to get this to work through some trial and error at https://github.com/jacobwgillespie/atlas-dockerfile-repro. Rather than overriding the `datadir`, which for some reason isn't working as expected when building in GitHub Actions, this PR updates the Dockerfile to just run the server once, then copy `/var/lib/mysql` to the final image.
This is successfully building at the test repo above.
cc @giautm
=> Fix generation of initialized DB in Dockerfile

sql/mysql/convert.go, sql/mysql/inspect.go
Small patch to attach table/column context to errors. See: https://github.com/ariga/atlas/issues/2019
=> sql/mysql: add table+column context to parse type errors

sql/internal/sqlx/plan.go, sql/internal/sqlx/plan_test.go
Although both (t1,t2)/(t2,t1) are valid orders when t1 and t2 do not depend each other, we want topsort to return consistent order by fallback to their names
=> sql/internal/sqlx: consistent order from topsort

cmd/atlas/internal/cmdapi/cmdapi_oss.go, cmd/atlas/internal/cmdapi/migrate_test.go, cmd/atlas/internal/cmdapi/project.go
The `url` is an optional parameter of the `cloud` block, making it possible to configure the target server.
=> cmd/atlas/internal: pass configured client to context setter

sql/postgres/diff.go
=> sql/postgres: fix panic in postgres DefaultDiffer func

cmd/atlas/internal/cloudapi/client.go, cmd/atlas/internal/cloudapi/client_test.go, cmd/atlas/internal/cmdapi/cmdapi.go, cmd/atlas/internal/cmdapi/migrate_test.go, cmd/atlas/internal/cmdext/cmdext.go, sql/sqlclient/client.go, sql/sqlclient/client_test.go
Before this PR, passing Atlas an invalid URL returned an error that includes the problematic URL (in `url.Error.URL`):
```shell
$ atlas schema inspect -u "  mysql://user:pass@:3306"
Error: parse "  mysql://user:pass@:3306": first path segment in URL cannot contain colon
```
This might be useful in local development, but it should be avoided, as Atlas is mostly used in CI/CD environments. This PR changes the behavior by introducing a new function (`sqlclient.ParseURL`) that returns parse errors without the raw URLs, and it is used by the various cmd packages. For example:
```
$ atlas schema inspect -u "  mysql://user:pass@:3306"
Error: first path segment in URL cannot contain colon
```
=> cmd/atlas: omit url strings from parse errors

sql/internal/specutil/convert.go, sql/internal/specutil/spec.go, sql/postgres/sqlspec.go, sql/postgres/sqlspec_test.go, sql/schema/dsl.go, sql/schema/schema.go, sql/sqlspec/sqlspec.go
Adding another type to HCL, `materialized`. The reason we don't use `view` is that, in different databases (PostgreSQL, MSSQL, DB2, etc.), these two don't have the same set of attributes and we want our LSP to enforce type safety without executing custom logic.
=> sql: add support for materialized views in sqlspec

cmd/atlas/internal/cmdapi/migrate.go, cmd/atlas/internal/cmdapi/schema.go, cmd/atlas/internal/cmdlog/cmdlog.go
Avoid using context background in templates
=> cmd/atlas: pass correct command context to log templates

sql/migrate/lex.go, sql/migrate/testdata/lex/6_skip_comment.sql, sql/migrate/testdata/lex/6_skip_comment.sql.golden
Next steps are two make the lexer driver-aware and move its config to the drivers
=> sql/migrate: skip non-standard #-based comments inside parens

cmd/atlas/internal/docker/docker.go, cmd/atlas/internal/docker/docker_test.go
Postgis is a commonly used GIS extension for Postgres and ships with its own published Docker images. Everything about Atlas works except for image name parsing for the Postgis images. This PR adds support for Postgis in the URL scheme.
=> Add support for postgis in --dev-url

doc/md/guides/deploying/k8s-argo.md, doc/md/guides/deploying/k8s-flux.md
gitops.tech is just a landing page for a commercial book
The correct page of the gitops working group is opengitops.dev
=> docs: use correct gitops link

cmd/atlas/internal/cmdext/cmdext.go, cmd/atlas/internal/cmdext/cmdext_test.go, schemahcl/schemahcl.go, schemahcl/schemahcl_test.go
Unlike TF, query is omitted and the result is returned as-is. A string that can be parsed and decoded by the jsondecode function
=> cmd/atlas/internal/cmdext: add support for 'extenral' data source

schemahcl/stdlib.go, schemahcl/stdlib_test.go
I want to be able to write such expressions:
```hcl
envfile = {
for line in split("\n", file(var.envfile)): split("=", line)[0] => regex("=(.*)", line)[0]
if !startswith(line, "#") && length(split("=", line)) > 1
}
```
=> schemahcl: add more tf functions to stdlib

cmd/atlas/internal/docker/docker.go, cmd/atlas/internal/docker/docker_test.go, doc/md/concepts/dev.mdx
Fixed https://github.com/ariga/atlas/issues/1678
- Support custom docker images
- Remove the implicit "docker pull" 
For example:
```shell
$ atlas schema inspect \
-u file://schema.sql \
--dev-url "docker+postgres://ankane/pgvector/dev"
table "t" {
schema = schema.public
column "c" {
null = true
type = integer
}
}
schema "public" {
comment = "standard public schema"
}
```
```shell
$ atlas schema inspect \
-u file://schema.sql \
--dev-url "docker+postgres://ankane/pgvector/dev?search_path=public" \
--format="{{ sql . \"  \" }}"
-- Create "t" table
CREATE TABLE "t" (
"c" integer NULL
);
```
=> cmd/atlas/internal/docker: allow custom images in docker driver

cmd/atlas/internal/cmdapi/cmdapi.go, cmd/atlas/internal/cmdapi/migrate.go, cmd/atlas/internal/cmdapi/project.go, cmd/atlas/internal/cmdapi/schema.go, cmd/atlas/internal/cmdapi/schema_test.go, doc/md/declarative/diff.mdx
Added support for the `env://` scheme, which allows for referencing attributes from the selected/current environment.
```shell
atlas schema diff --env drift --from env://state1 --to env://state2
atlas migrate diff --env dev --to env://state1
```
In the future, we can also add support for something like this `flags` block:
```hcl
env {
flags {
schema {
from = "..."
to   = "..."
}
}
}
```
=> cmd/atlas/internal/cmdapi: support reference env:// attributes

sql/postgres/migrate.go, sql/postgres/migrate_test.go
=> sql/postgres: support add enum values before/after exisiting values

cmd/atlas/internal/cmdapi/cmdapi.go, cmd/atlas/internal/cmdapi/migrate.go, cmd/atlas/internal/cmdapi/schema.go
This will allow us to work with proper types instead of configure output inside the commands
=> cmd/atlas/internal/cmdapi: hook into RunE execution

doc/md/versioned/apply.mdx
Fix broken link.
https://atlasgo.io/versioned/apply
=> Fix link of `atlas migrate lint`

.github/workflows/ci-go_oss.yaml, cmd/atlas/internal/cmdapi/cmdapi.go, cmd/atlas/internal/cmdapi/migrate.go, cmd/atlas/internal/cmdapi/migrate_test.go, cmd/atlas/internal/cmdapi/project.go, cmd/atlas/internal/cmdapi/project_test.go, doc/md/atlas-schema/projects.mdx, doc/md/reference.md, doc/md/versioned/apply.mdx, doc/website/docusaurus.config.js, go.mod, internal/ci/jobs_oss.go, sql/migrate/migrate.go, sql/migrate/migrate_test.go, sql/sqltool/tool.go
Also, changing the default behavior to error (instead of skip) in case non-linear history
(cmd tests will be pushed soon)
=> sql/migrate: support controlling the execution order

cmd/atlas/internal/cmdlog/cmdlog.go, internal/integration/testdata/sqlite/cli-migrate-apply.txt
Previously, if applying migration files which statements that contained new lines, it looked like this:
After this change it is properly indented:
=> cmd/atlas/internal/cmdlog: indent new line in apply log

schemahcl/schemahcl.go
**before**:
memory:
[before.pdf](https://github.com/ariga/atlas/files/13539225/before.pdf)
**after**:
memory:
[mem_after.pdf](https://github.com/ariga/atlas/files/13539221/mem_after.pdf)
=> schemahcl: fix memory leak in patchRefs func

schemahcl/context.go, schemahcl/extension.go, schemahcl/schemahcl.go, sql/postgres/sqlspec.go, sql/postgres/sqlspec_test.go
```
benchmark              old ns/op     new ns/op     delta
BenchmarkSchema-16     569319394     238469401     -58.11%
benchmark              old allocs     new allocs     delta
BenchmarkSchema-16     1327927        1174085        -11.59%
benchmark              old bytes     new bytes     delta
BenchmarkSchema-16     293956792     186829161     -36.44%
```
=> schemahcl: reduce eval mem usage

sql/internal/sqlx/plan.go, sql/internal/sqlx/plan_test.go
Triggers are not explicitly dropped as they are dropped together with the table they attach to
=> sql/internal/sqlx: indirect drop trigger dropping

doc/md/support.mdx, doc/website/docusaurus.config.js, doc/website/sidebars.js
=> doc/md: support page

sql/sqlite/migrate.go
I found that the syntax for the `DROP TABLE IF EXISTS` is not correct for sqlite.
https://www.sqlite.org/lang_droptable.html
=> sql/sqlite: Fix DROP TABLE IF EXISTS

cmd/atlas/internal/cmdlog/cmdlog.go, cmd/atlas/internal/migrate/report.go
Also removed (non-working) format function
=> cmd/atlas/internal/cmdapi: use driver-aware statement scanning in migrate status

cmd/atlas/internal/docker/docker.go
```
$ ./cmd/atlas/atlas schema diff \
--from "sqlserver://sa:P@ssw0rd0995@:1433?database=master" \
--to "file://schema.hcl" \
--dev-url "docker://sqlserver/2022-latest/dev?v=1"
8ac741c3cf2b889df6fbf0f9787f0150ff2c95b00a4d247660bab1f399efa85c
Waiting for service to be ready ... 
Error: timeout: login is required to use the 'sqlserver' beta driver. See: https://atlasgo.io/cloud/beta-drivers: <nil>
```
=> cmd/docker: print latest error when timeout

doc/md/guides/guides.mdx, doc/md/guides/postgres/pg-110.md, doc/md/lint/analyzers.mdx, doc/website/sidebars.js
=> doc/md: rename postgres alignment analyzer from ar101 to pg110

sql/internal/specutil/convert.go, sql/internal/sqlx/plan.go, sql/postgres/sqlspec_test.go
- sql/sqlx: respect type in deps list of func/proc
- sql/specutil: sort `depends_on` by used its name
=> sql/sqlx: respect type in deps list of func/proc

cmd/atlas/internal/cmdapi/migrate.go
Also, use path instead of filepath for dir slugs
=> cmd/atlas/internal: minor naming changes

cmd/atlas/internal/cmdapi/migrate.go, cmd/atlas/internal/cmdapi/migrate_test.go, cmd/atlas/internal/migratelint/run_test.go, sql/migrate/dir.go, sql/migrate/dir_test.go
The first line is the global hash, first file is one line 2, not 1.
=> sql/migrate: fix incorrect line number in checksum error

cmd/atlas/internal/migrate/migrate.go, cmd/atlas/internal/migrate/migrate_test.go
=>  cmd/atlas/internal: show more detailed error msg when scheme is not provided to --dir

cmd/atlas/internal/migratelint/lint_oss.go
sqlclient.Client is migrate.Driver but hide all extra methods implemented by the underlying driver.
Fixed https://github.com/ariga/atlas/issues/2699
=> cmd/atlas/internal/migratelint: passing underlying driver to scanner

sql/internal/sqlx/plan.go
when I want to add feature for linter [makezero](https://github.com/ashanbrown/makezero) , so I run some github action for real world repos, and the action report this bug.
=> sql/sqlx: fix miss makezero bug with `byKeys` sort

schemahcl/context.go, schemahcl/schemahcl.go
```
benchmark                old ns/op     new ns/op     delta
Benchmark_EvalHCL-16     196478424     170294770     -13.33%
benchmark                old allocs     new allocs     delta
Benchmark_EvalHCL-16     1069863        926489         -13.40%
benchmark                old bytes     new bytes     delta
Benchmark_EvalHCL-16     133138506     122031348     -8.34%
```
=> schemahcl: speedup eval schemas

internal/integration/postgres_test.go, sql/postgres/inspect.go, sql/postgres/inspect_test.go
When operating on realm-scope we expect all objects to be qualified. However, the default configuration of pg sets the search_path to `$user, public` causes all references to public objects to return from pg_catalog without qualifiers.
=> sql/postgres: unset default search_path

cmd/atlas/internal/cmdapi/migrate.go
`data.remote_dir` used to map to `mem://`-based directory. That's not the case anymore.
=> cmd/atlas/internal/cmdapi: report migrate for remote dir only

internal/integration/hclsqlspec/hclsqlspec_test.go, sql/sqlspec/sqlspec.go
This reverts commit f8a15b3aa05455cac4de72fd30bcc6c07969d2e5.
=> sql/sqlspec: Revert support `name` attribute on the table resource (#2820)

cmd/atlas/internal/cmdlog/cmdlog.go, cmd/atlas/internal/cmdlog/cmdlog_test.go, sql/migrate/migrate.go
=> cmd/atlas/internal/cmdlog: detect and print error during migrate plan

doc/md/atlas-schema/hcl.mdx
=> doc/md/atlas-schema: add clickhouse hcl syntax for primary key expressions

cmd/atlas/internal/cmdapi/migrate.go, internal/integration/testdata/mysql/cli-migrate-diff-mode-normalized.txt, sql/internal/sqlx/diff.go, sql/migrate/migrate.go, sql/mysql/diff.go, sql/postgres/crdb.go, sql/schema/migrate.go, sql/sqlite/diff.go
If the input to diffing is already normalized, we can skip manual normalization that as in place before there was the dev connection.
=> sql/schema: add diff mode

cmd/atlas/internal/cloudapi/client.go, cmd/atlas/main.go, cmd/atlas/main_oss.go
=> cmd/atlas: extendctx can return an error

cmd/atlas/go.mod, go.mod, internal/integration/go.mod
Fix CVE-2024-24791. Updating "just" the toolchain is not enough.
=> all: update go version

cmd/atlas/internal/cmdapi/project.go
=> cmd/atlas/internal/cmdapi: add repo block to schema/migration

cmd/atlas/internal/cmdext/reader.go, cmd/atlas/internal/cmdlog/cmdlog.go, cmd/atlas/internal/migratelint/run.go, sql/migrate/dir.go, sql/migrate/dir_test.go
Avoid `len` checks whenever `Format` is called on the default template.
=> sql/migrate: add FormatFile for TemplateFormatter

doc/md/integrations/kubernetes/operator.mdx
If it's the old `cloud { project = ... }` attribute, it's irrelevant atm.
=> doc: remove irrelevant project param from operator config

cmd/atlas/internal/cmdapi/project.go, cmd/atlas/internal/cmdapi/project_test.go
Just for convenience, we should support these standard attributes.
=> cmd/atlas/internal/cmdapi: support schema attrs in env:// references

sql/internal/specutil/convert.go, sql/internal/sqlx/diff.go, sql/internal/sqlx/sqlx.go, sql/mysql/diff.go, sql/schema/dsl.go, sql/schema/schema.go, sql/sqlite/diff.go
=> sql/internal/sqlx: allow extending diff with fk attributes

cmd/atlas/internal/cmdapi/cmdapi.go, sql/internal/sqlx/diff.go, sql/mysql/diff.go, sql/postgres/driver_oss.go, sql/sqlite/diff.go
=> sql/internal/sqlx: pass diff options to drivers

cmd/atlas/internal/migratelint/lint.go
If the connection is scoped to a specific schema, we should use InspectSchema to get the inspected realm. That is because PostgreSQL unsets the search_path when inspecting the entire realm, causing us to lose the schema context and get qualified composite types on inspection.
Fixed https://github.com/ariga/atlas/issues/3200
=> cmd/atlas/internal/migratelint: make linting inspection context-aware

cmd/atlas/internal/cmdapi/cmdapi_oss.go, sql/internal/sqlx/diff.go, sql/mysql/diff.go, sql/postgres/diff_oss.go, sql/sqlite/diff.go
Until now, checks were skipped in comparisons before dev-databases was a thing in Atlas. Now, that dev-databases are a standard (must-have) thing in Atlas, objects are ~always normalized, allowing us to consistently compare expressions.
**Approved internally.**
=> sql: support diffing check expressions when diff is normalized

sql/postgres/migrate_oss.go, sql/postgres/migrate_oss_test.go
I noticed this error while using the ent.
The collation of the migration file generated using `migrate.NamedDiff` in ent will be output without double quotation marks. The following error occurs when migrating the generated file.
```sh
ERROR:  syntax error at or near "-"
LINE 255: ...ALTER COLUMN "name" TYPE text COLLATE ja-x-icu;
```
The same error occurs if the collation contains a dot in the collation will also cause an error.
e.g. `en_US.UTF-8`
The version in which I found this error is a bit old, but I believe it reproduces in the latest version.
- ariga.io/atlas v0.19.1-0.20240203083654-5948b60a8e43
- entgo.io/ent v0.13.1
The fix for the cause of this error is L820. The other two were mechanically corrected because they were using COLLATE.
=> fix: an error that occurs when collation contains hyphen or dot

internal/integration/testdata/postgres/column-generated.txt
=> internal/integration/postgres: skip generated columns test in version 17

sql/migrate/lex.go, sql/migrate/lex_test.go, sql/migrate/testdata/lex/19_ms_gocmd.sql, sql/migrate/testdata/lex/19_ms_gocmd.sql.golden, sql/migrate/testdata/lex/20_ms_go-delim.sql, sql/migrate/testdata/lex/20_ms_go-delim.sql.golden
The newline character can be a part of statement delimiter
=> sql/migrate: support `GO` command in lexer

sql/migrate/migrate.go, sql/migrate/migrate_test.go
Closed https://github.com/ariga/atlas/issues/3308
=> sql/migrate: clean up error from revisions table when retry pass

internal/integration/script_test.go
=> internal/integration: fixed newline for diff

sql/sqlite/diff_test.go, sql/sqlite/driver.go, sql/sqlite/driver_test.go, sql/sqlite/inspect_test.go, sql/sqlite/migrate_test.go
The package is static and updated whenever we update the package
=> sql/sqlite: remove query to sqlite_version()

schemahcl/spec.go, sql/postgres/driver.go
=> sql/postgres: add storage params constants

sql/internal/sqlx/sqlx.go
currently, `.NL().P("FOO")` write ` FOO` in the new line, this commit remove the space before `FOO`
=> sql/sqlx: fix spacing on the new lines

cmd/atlas/internal/migrate/migrate.go
Currently, this change applies only to neon and supabase and fixes: https://github.com/ariga/atlas/issues/2509. However, we plan to migrate away from entmigrate to driver-specific store. This way, we can detect other poolers such as pgbouncer.
=> cmd/atlas/internal/migrate: use schema qualifier for pooler-based pg services

internal/integration/hclsqlspec/hclsqlspec_test.go, sql/internal/specutil/convert.go, sql/postgres/sqlspec_oss.go, sql/schema/schema.go, sql/sqlspec/sqlspec.go
```hcl
table "t1" {
column "c1" {
type = int
default "DF__t1__c1" {
as = 1
}
}
}
```
=> sql/sqlspec: support named default values for table columns

sql/sqltool/tool.go, sql/sqltool/tool_test.go
The parent can be local directory, that takes all files - including `.down.sql` for golang-migrate format.
Ref: https://github.com/ariga/atlas/pull/1642, https://github.com/ariga/atlas/pull/1652
=> sql/sqltool: remove call to parent `Checksum()`

cmd/atlas/internal/cmdapi/cmdapi.go
=> cmd/atlas/internal/cmdapi: unwrap abort error

internal/integration/script_test.go
This is needed for `atlas schema inspect --url='file://migrations' --dev-url='docker://clickhouse' > schema.hcl` works in testscript.
Because atlas will looking for `docker` binary in `$PATH` environment.
=> internal/integration: share `$PATH` with command when execute with output redirect

internal/ci/ci_dialect.tmpl, internal/ci/main.go
this code:
```go
Steps: []Step{
{
Name:   "Run CockroachDB",
Action: "docker",
With: []string{
"args: run",
},
},
{
Name: "Run Atlas",
Run: "echo 'CREATE DATABASE test\n" +
"echo 'CREATE DATABASE test2'",
},
},
```
will generate the next steps:
```yaml
+      - name: Run CockroachDB
+        uses:  docker
+        with:
+          args: run
+      - name: Run Atlas
+        run: |
+          echo 'CREATE DATABASE test
+          echo 'CREATE DATABASE test2'
```
=> internal/ci: support running custom code in generated ci steps

sql/internal/specutil/convert.go, sql/internal/sqlx/plan.go
=> sql/internal/sqlx: allow drivers checking if proc depends on object

sdk/recordriver/driver.go, sdk/recordriver/driver_test.go
https://github.com/ariga/atlas/pull/3543/commits/57a6901a943526c5df2dd1152a5edb2c0affe9af
I mistakenly changed the function to follow the linter, without considering backward compatibility. This PR reverts it back.
=> sdk/recorddriver: rename Session type to session for consistency

cmd/atlas/internal/docker/docker.go
Add condition to use hostname only for tcp or ssh schemes.
=> cmd/atlas/docker: fix hostname for `unix` protocol
