sql/sqlspec/sqlspec.go

(will remove from sql/schemaspec subsequently)

sql/sqlspec: adding virtual types 

---

sql/sqlite/sqlspec_test.go

 sql/sqlite: unmarshal spec column types

---

cmd/atlas/apply.go
cmd/atlas/diff.go
cmd/atlas/diff_test.go
cmd/atlas/mux.go
cmd/atlas/provider.go

cmd/atlas: diff printing

---

cmd/atlas/apply.go
cmd/atlas/inspect.go
cmd/atlas/mux.go
cmd/atlas/schema.go

- includes all changes in review (doesn't include postgress errors found today).

cli/atlas: product review

---

doc/md/CLI/getting_started.mdx

doc/cli: extend getting started

---

schema/schemaspec/extension.go

cleaning up this portion of the code that got a bit ugly.

schema/schemaspec: cleaning up field descriptor code for extensions

---

internal/integration/mysql_test.go

- internal/integration/mysql: use hcl to structure db
- internal/integration/mysql: add apply test

internal/integration: cli apply test 

---

cmd/internal/base/diff_test.go
doc/md/sql.md
internal/integration/hclsqlspec/hclsqlspec_test.go
internal/integration/mysql_test.go
internal/integration/postgres_test.go
internal/integration/sqlite_test.go
sql/internal/specutil/convert.go
sql/internal/specutil/convert_test.go
sql/mysql/sqlspec_test.go
sql/postgres/sqlspec_test.go
sql/sqlite/sqlspec_test.go
sql/sqlspec/sqlspec.go

sql/sqlspec: changing Table.Schema to be a schemspec.Ref and fixing tests

---

schema/schemaspec/schemahcl/context_test.go
schema/schemaspec/schemahcl/hcl.go
schema/schemaspec/schemahcl/opts.go

and adding the MarshalSpec method.

schema/schemaspec/schemahcl: renaming the Unmarshaler type to state 

---

internal/integration/sqlite_test.go

- internal/integration: extend postgres testing
- internal/integration: test sqlite

internal/integration: test sqlite

---

cmd/action/apply.go
cmd/action/diff.go
cmd/action/diff_test.go
cmd/action/mux.go
cmd/action/provider.go
internal/integration/mysql_test.go
internal/integration/postgres_test.go
internal/integration/sqlite_test.go
sql/migrate/migrate.go
sql/mysql/driver.go
sql/mysql/migrate.go
sql/mysql/migrate_test.go
sql/postgres/driver.go
sql/postgres/migrate.go
sql/postgres/migrate_test.go
sql/schema/migrate.go
sql/sqlite/driver.go
sql/sqlite/migrate.go
sql/sqlite/migrate_test.go

Replaced with migrate.ApplyChanges

all: remove schema.Execer

---

internal/integration/integration_test.go
internal/integration/mysql_test.go
internal/integration/postgres_test.go
internal/integration/sqlite_test.go

more tests fixed.
(still those stuck on `text[]`)

internal/integration: updating integration tests

---

sql/internal/sqlx/plan.go
sql/mysql/migrate.go
sql/postgres/migrate.go
sql/sqlite/migrate.go

And move to sqlx (rule of three)

sql: use change.Comment on apply failure

---

sql/internal/specutil/convert.go
sql/mysql/sqlspec.go
sql/postgres/sqlspec.go
sql/sqlite/sqlspec.go

found a bug with handling column default. small PR before so all drivers share the fix

sql/internal/specutil: sharing from column to columnspec code

---

internal/integration/hclsqlspec/hclsqlspec_test.go
internal/integration/mysql_test.go
internal/integration/postgres_test.go
sql/internal/specutil/convert.go
sql/internal/specutil/spec.go
sql/mysql/sqlspec.go
sql/mysql/sqlspec_test.go
sql/postgres/sqlspec.go
sql/sqlite/sqlspec.go

first PR towards multi-schema support.

sql/mysql: support realm marshal and unmarshal

---

sql/schema/dsl.go
sql/schema/dsl_test.go
sql/schema/schema.go

This DSL is still in an "experiment mode", but I plan to stabilize it after finishing the integration with ent.

sql/schema: initial implementation for fluent api

---

sql/mysql/diff.go
sql/mysql/migrate.go
sql/postgres/migrate.go

sql/mysql: fix the way we ignore indexes that were created automatically by foreign-keys

---

sql/internal/sqlx/diff.go
sql/mysql/diff.go
sql/mysql/diff_test.go
sql/mysql/migrate.go
sql/mysql/migrate_test.go

- sql/mysql: detect index-prefix change on diff
- sql/mysql: apply index sub-part attribute on migrate

sql/mysql: index sub parts

---

internal/integration/hclsqlspec/hclsqlspec_test.go
sql/internal/specutil/convert.go
sql/mysql/sqlspec_test.go
sql/postgres/sqlspec_test.go
sql/schema/dsl.go
sql/schema/dsl_test.go
sql/sqlite/sqlspec_test.go
sql/sqlspec/sqlspec.go

Please note, that the changes to the Marshal test is necessary until I implement the Marshal method for comments.

sql/sqlspec: add comment fields to table, column and index structs

---

sql/internal/specutil/convert.go
sql/mysql/sqlspec.go
sql/mysql/sqlspec_test.go

Put inline interface into its own type

beautify code

---

doc/website/src/pages/index.js
doc/website/src/pages/index.module.css

additionally, remove CSS err thrown in the console and rescale desktop media query.

doc/website: fix build issue caused by using navigator. 

---

doc/website/src/pages/index.js

wrapped with the BrowserOnly tag.

doc/website: fix build issue caused by using window - due to SSR build.

---

internal/integration/mysql_test.go
sql/internal/sqlx/sqlx.go
sql/mysql/driver.go
sql/mysql/inspect.go
sql/mysql/inspect_test.go
sql/postgres/diff.go
sql/postgres/driver.go
sql/postgres/inspect.go
sql/schema/inspect.go
sql/sqlite/driver.go
sql/sqlite/inspect_test.go
sql/sqlite/migrate.go

Make it simpler to implement it by tools like Ent

sql/schema: simplify the ExecQuerier interface.

---

doc/md/getting-started/01-introduction.mdx

Fixed installation command for windows as mentioned by #440

doc/website: update windows getting started

---

internal/integration/go.mod
internal/integration/go.sum
internal/integration/integration_test.go
internal/integration/mysql_test.go
internal/integration/testdata/mysql/add-drop-column.txt
internal/integration/testdata/mysql/add-drop-index.txt
internal/integration/testdata/mysql/add-foreign-key.txt
sql/mysql/inspect.go
sql/mysql/inspect_test.go
sql/mysql/migrate.go

If you're not familiar with `testscript`, please see https://github.com/golang/go/blob/master/src/cmd/go/testdata/script/README and https://pkg.go.dev/github.com/rogpeppe/go-internal/testscript. 
I plan to start writing all tests with this form and move most others to it (already found a bug with it).

internal/integration: initial testing using testscript

---

doc/website/docusaurus.config.js

doc: revert favicon url

---

sql/internal/sqlx/sqlx.go
sql/mysql/inspect.go
sql/mysql/inspect_test.go
sql/schema/dsl.go

`ScanSchemaFKs` and `ScanFKs` will be merged together after I'll rewrite PostgreSQL.

sql/mysql: same inspection, but faster

---

doc/md/getting-started/01-introduction.mdx

doc/website: add section about latest release

---

sql/migrate/migrate.go
sql/migrate/migrate_test.go
sql/migrate/testdata/1.sql

~~Will be rebased once #566 is merged.~~

sql/migrate: add GlobStateReader

---

sql/mysql/migrate.go
sql/mysql/migrate_test.go
sql/mysql/normalize.go
sql/mysql/normalize_test.go
sql/schema/inspect.go

You know the context. I'll add more docs to it after I'll push the rest of the implementation for the other drivers.

sql/mysql: mysql implementation for schema.Normalize

---

sql/postgres/inspect.go
sql/postgres/migrate.go
sql/postgres/migrate_test.go

Also, add support for `DROP ... CASCADE` statements.

sql/postgres: fix statements generation when IfExists/IfNotExists is used

---

internal/integration/tidb_test.go
sql/mysql/tidb.go

Not many integration tests are left. namely:
TestTiDB_Ent  
TestTiDB_HCL  
TestTiDB_CLI  
TestTiDB_CLI_MultiSchema

sql/tidb: add more integration tests

---

.github/workflows/ci.yml
.golangci.yml
cmd/action/fmt_test.go
cmd/action/internal/update/update.go
sql/internal/sqlx/twin.go
sql/migrate/migrate.go

sql/sqlx: replace md5 hash and run gosec on ci

---

internal/integration/testdata/mysql/index-prefix.txt
sql/internal/specutil/convert.go
sql/internal/specutil/spec.go
sql/mysql/sqlspec.go
sql/mysql/sqlspec_test.go

See: https://dev.mysql.com/doc/refman/8.0/en/column-indexes.html\#column-indexes-prefix

sql/mysql: add support for index prefixes

---

internal/integration/integration_test.go
internal/integration/mysql_test.go
internal/integration/postgres_test.go
sql/internal/sqlx/dev.go
sql/internal/sqlx/sqlx.go
sql/mysql/driver.go
sql/mysql/driver_test.go
sql/postgres/driver.go
sql/postgres/driver_test.go
sql/schema/migrate.go

Please, don't review yet. Working on integration tests.

sql/postgres: implement schema.Locker

---

schema/schemaspec/extension.go
schema/schemaspec/schemahcl/hcl.go
schema/schemaspec/schemahcl/hcl_test.go

* marshal qualifiers to HCL
* schemaspec.Extension Scan handles qualifier fields

schema/schemaspec: marshal qualifers

---

sql/mysql/migrate.go

sql/mysql: simplify alter table function

---

sql/sqlite/driver.go
sql/sqlite/inspect.go
sql/sqlite/inspect_test.go

For more info, see [sqlite/sqlite/src/pragma.c](https://github.com/sqlite/sqlite/blob/171c50ec381c5fb4ff1e8b258a49fbf810917011/src/pragma.c#L1109-L1112).

sql/sqlite: support inspecting generated columns

---

doc/website/blog/2021-11-25-meet-atlas.md
doc/website/blog/2022-01-19-atlas-v030.md
doc/website/blog/2022-02-01-atlas-v032-multi-schema.md
doc/website/blog/2022-02-09-programmatic-inspection-in-go-with-atlas.md
doc/website/docusaurus.config.js
doc/website/package-lock.json
doc/website/package.json
doc/website/src/css/custom.css
doc/website/src/pages/index.js

* added blog page
* brought relevant posts from ariga.io
* fixed SQL syntax highlight

doc/website: add blog page

---

doc/website/docusaurus.config.js
doc/website/src/css/custom.css
doc/website/src/pages/index.module.css

doc/website: add banner

---

doc/website/docusaurus.config.js

doc/website: add Algolia search bar

---

doc/md/cli/reference.md
doc/md/deployment/intro.md
go.sum
package-lock.json

Update that the UI is currently unavailable in the serve command and part of the deployment .

doc/md: update UI command docs

---

sql/postgres/driver.go
sql/postgres/inspect.go

Revert "sql/cockroach: make postgres inspect compatible with crdb"

---

doc/md/getting-started/03-applying.md

doc/md: fix flag to -u

---

cmd/atlascmd/schema.go
internal/integration/script_test.go
internal/integration/testdata/mysql/cli-project-schemas.txt

fix schema selection bug reported

cmd/atlascmd: fix schema selection from env

---

cmd/atlasci/internal/ci/run.go
cmd/atlasci/internal/ci/run_test.go
sql/sqlcheck/sqlcheck.go
sql/sqlcheck/sqlcheck_test.go

This is an example implementation (that I'm going to stabilize) to demonstrate how to write a driver-aware analyzer.

sql/sqlcheck: add first basic analyzer

---

internal/integration/testdata/postgres/index-unique-constraint.txt
sql/postgres/inspect.go
sql/postgres/migrate.go
sql/postgres/migrate_test.go

sql/postgres: support dropping unique constraints

---

cmd/atlasci/internal/ci/ci.go
cmd/atlasci/internal/ci/ci_test.go
cmd/atlasci/internal/ci/run.go
sql/migrate/migrate.go

Allow reading the files multiple times.

sql/migrate: change Read to Bytes in File interface.

---

doc/md/ci/analyzers.md
doc/md/lint/analyzers.md
sql/sqlcheck/sqlcheck.go

Currently not connecting it to the navigation in the website.

doc/md: documenting sqlcheck analyzers

---

internal/integration/testdata/mysql/column-default-expr.txt
sql/mysql/inspect.go
sql/mysql/inspect_test.go

Closed https://github.com/ariga/atlas/issues/803.

sql/mysql: unescape mysql expression strings

---

cmd/atlas/internal/cmdapi/diff.go
cmd/atlas/internal/cmdapi/migrate.go
cmd/atlas/internal/cmdapi/schema.go

Make dev-url flag required to avoid getting the following error:

cmd/atlas/internal/cmdapi: miscellaneous changes while running manual testing

---

.github/workflows/ci.yml
internal/ci/ci.tmpl
internal/integration/hclsqlspec/hclsqlspec_test.go

@rotemtam I fond that one test was not run in the CI. I enabled that one and I am not sure if this test is obsolete. Please have a look.

internal/integration: enabled missing tests

---

cmd/atlas/internal/cmdapi/migrate.go
doc/md/cli/reference.md

cmd/atlas/internal/cmdapi: update migrate status command to be aware of partially applied files

---

doc/website/src/pages/index.js

https://user-images.githubusercontent.com/73284641/179393319-7c9b81f5-5841-4628-814b-d6be8895f5b7.mov
Removed the UI section between the ERD and Ent.

doc/website/src: remove UI from landing page

---

doc/md/cli/projects.md
doc/md/concepts/dev.md
doc/md/concepts/url.mdx
doc/md/ddl/sql.mdx
doc/website/blog/2022-05-04-announcing-terraform-provider.md
doc/website/blog/2022-07-14-announcing-atlas-lint.md
doc/website/docusaurus.config.js
doc/website/sidebars.js

* Added new directory "concepts"
* Moved Dev Database & URLs into "Concepts"

doc: add concepts

---

doc/md/ddl/sql-types.md
sql/sqlite/convert.go
sql/sqlite/migrate.go
sql/sqlite/migrate_test.go
sql/sqlite/sqlspec.go

sqlite: miscellaneous changes (doc, migrate, sqlspec) 

---

doc/website/docusaurus.config.js

docs: fix footer link

---

doc/md/integrations/terraform.md

doc/md: fix link

---

schemahcl/context_test.go
schemahcl/opts.go

Closes https://github.com/ariga/atlas/issues/1001.

schemahcl: dont allow empty str sql() expr

---

internal/integration/postgres_test.go

I spent so much time debugging PostgreSQL code, while the issue was different - `migrate diff` was overriding my files.

internal/integration: finish testing for migrate diff

---

internal/integration/mysql_test.go
internal/integration/postgres_test.go
sql/internal/specutil/convert.go
sql/internal/specutil/spec.go
sql/mysql/sqlspec_test.go
sql/postgres/sqlspec.go
sql/postgres/sqlspec_test.go

sql: support cross-schema references in HCL

---

doc/md/lint/analyzers.md
sql/sqlcheck/datadepend/datadepend.go

all: rename dependant to dependent

---

cmd/atlas/internal/cmdapi/migrate.go
sql/migrate/migrate.go
sql/migrate/migrate_test.go

Integration tests will follow once the status command has been updated

sql/migrate: set operator version from CLI on migrate apply

---

README.md

Typo fix for `Supported Databases` in Readme

---

doc/md/atlas-schema/sql.mdx
internal/integration/testdata/postgres/index-include.txt
schemahcl/spec.go
sql/postgres/diff.go
sql/postgres/diff_test.go
sql/postgres/driver.go
sql/postgres/inspect.go
sql/postgres/inspect_test.go
sql/postgres/migrate.go
sql/postgres/migrate_test.go
sql/postgres/sqlspec.go
sql/postgres/sqlspec_test.go

https://github.com/ent/ent/issues/2905

sql/postgres: support index INCLUDEd columns

---

cmd/atlas/internal/cmdapi/cmdapi.go
cmd/atlas/internal/cmdapi/project.go
cmd/atlas/internal/cmdapi/project_test.go
cmd/atlas/internal/cmdapi/schema.go
doc/md/reference.md
internal/integration/hclsqlspec/hclsqlspec_test.go
schemahcl/context.go
schemahcl/context_test.go
schemahcl/hcl.go
schemahcl/hcl_test.go
sql/internal/spectest/spectest.go
sql/internal/specutil/spec.go
sql/mysql/sqlspec.go
sql/postgres/sqlspec.go
sql/sqlite/sqlspec.go

Also, use the native cty.Value type in our codebase

schemahcl: accept list(T) as inputs

---

doc/md/guides/postgres/included-columns.md

Minor fix in postgres/included-columns.md

doc/md/guides: Minor fix in included-columns.md

---

doc/md/cloud/getting-started.md

doc/md: add image to cloud doc

---

internal/integration/testdata/postgres/column-domain.txt
sql/postgres/convert.go
sql/postgres/inspect.go
sql/postgres/inspect_test.go

Fixed https://github.com/ariga/atlas/issues/1186.

sql/postgres: support inspecting domains as user-defined types

---

doc/md/cloud/getting-started.md

doc/md: fix screenshot in cloud docs

---

sql/internal/sqlx/sqlx.go
sql/internal/sqlx/sqlx_test.go

sql/internal: check balanced quoting

---

doc/website/docusaurus.config.js
doc/website/src/theme/BlogPostPage/Metadata/index.js
doc/website/src/theme/DocItem/Metadata/index.js
doc/website/src/theme/share-image.js

components created by "swizzling" : 
* doc/website/src/theme/BlogPostPage/Metadata/index.js
* doc/website/src/theme/DocItem/Metadata/index.js
see: https://docusaurus.io/docs/swizzling

doc/website: automatic share image generation

---

doc/website/src/pages/index.js

doc/website: update Atlas hero image

---

cmd/atlas/go.mod
cmd/atlas/go.sum
cmd/atlas/internal/cmdapi/migrate.go
cmd/atlas/internal/cmdapi/migrate_test.go
cmd/atlas/internal/migrate/report.go
cmd/atlas/internal/migrate/report_test.go
internal/integration/script_test.go
internal/integration/testdata/mysql/cli-migrate-apply.txt
sql/migrate/migrate.go
sql/migrate/migrate_test.go

default
`--log '{{ json . "  " }}`
```json
{
"Report": null,
"Driver": "sqlite3",
"URL": {
"Scheme": "sqlite",
"Opaque": "",
"User": null,
"Host": "",
"Path": "",
"RawPath": "",
"OmitHost": false,
"ForceQuery": false,
"RawQuery": "mode=memory",
"Fragment": "",
"RawFragment": "",
"DSN": "file:sqlite:?mode=memory",
"Schema": "main"
},
"Dir": "../../build/migrations",
"Pending": [
{
"Name": "1_changes.sql",
"Version": "1",
"Description": "changes"
},
{
"Name": "2_asd.sql",
"Version": "2",
"Description": "asd"
}
],
"Applied": [
{
"Name": "1_changes.sql",
"Version": "1",
"Description": "changes",
"Start": "2022-10-18T10:14:51.207977718+02:00",
"End": "2022-10-18T10:14:51.208411998+02:00",
"Stmts": [
"CREATE TABLE `users` (`id` bigint NOT NULL, `name` varchar(255) NOT NULL, PRIMARY KEY …
```

cmd/atlas/internal/cmdapi: make migrate apply logging template based

---

doc/md/atlas-schema/projects.md
internal/integration/testdata/mysql/cli-migrate-apply-datasrc.txt
schemahcl/stdlib.go
schemahcl/stdlib_test.go

schemahcl: added `urlsetpath` func to support change DB schema

---

internal/integration/testdata/postgres/cli-migrate-apply-datasrc.txt
schemahcl/stdlib.go
schemahcl/stdlib_test.go

schemahcl: added `urlqueryset` function

---

sql/spanner/inspect_test.go

Removes unnecessary CheckNamedValue method.

sql/spanner: remove unnecessary CheckNamedValue method

---

cmd/atlas/internal/cmdapi/cmdapi.go
cmd/atlas/internal/cmdapi/schema.go
cmd/atlas/internal/cmdapi/schema_test.go

Test failed before changes.
Fix #1224

cmd/atlas/internal/cmdapi: do not normalize without dev connection

---

.github/workflows/ci.yml
internal/ci/main.go
internal/integration/spanner_test.go
sql/spanner/sqlspec.go

This brings this test closer in line with the upstream test.

integration/spanner: expand the add/drop integration test

---

cmd/atlas/internal/sqlparse/myparse/myparse.go
cmd/atlas/internal/sqlparse/myparse/myparse_test.go

Next PRs will add some code for adding it to the MySQL analyzers.
> MySQL parses but ignores “inline REFERENCES specifications” (as defined in the SQL standard) where the references are defined as part of the column specification. MySQL accepts REFERENCES clauses only when specified as part of a separate FOREIGN KEY specification

cmd/atlas/sqlparse: add mysql parse logic for checking if column has inline fk def

---

internal/integration/spanner_test.go
sql/spanner/convert.go
sql/spanner/sqlspec.go

This includes fixing up column parsing which this test surfaced as having a few issues.

integration/spanner: Add HCL integration test

---

cmd/atlas/internal/docker/docker.go
cmd/atlas/internal/docker/docker_test.go
doc/md/concepts/url.mdx

Fixed https://github.com/ariga/atlas/issues/1250.

cmd/atlas/internal/docker: allow setting database name in url

---

internal/integration/spanner_test.go
sql/spanner/migrate.go

This expands the integration tests and starts support for *schema.ModifyTable

sql/spanner: Add AddColumns integration test, initial modifyTable, alterTable

---

cmd/atlas/internal/cmdapi/schema.go

Fixed https://github.com/ariga/atlas/issues/1269.

cmd/atlas: accept 'schema clean' on realms

---

cmd/atlas/internal/cmdapi/schema.go
cmd/atlas/internal/cmdapi/schema_test.go

Fixed https://github.com/ariga/atlas/issues/1252

cmd/atlas: support reading config files in 'schema diff' command

---

cmd/atlas/internal/cmdapi/project.go
cmd/atlas/internal/cmdapi/schema.go
cmd/atlas/internal/cmdapi/schema_test.go

Fixed https://github.com/ariga/atlas/issues/1278

cmd/atlas: support list of schemas in env.src

---

internal/integration/testdata/mysql/column-charset.txt
sql/schema/dsl.go
sql/schema/dsl_test.go

A small helper I need to use in Ent's codebase.

sql/schema: add RemoveAttr helper to schema dsl

---

cmd/atlas/internal/cmdapi/migrate.go
internal/integration/mysql_test.go
internal/integration/testdata/migrations/mysqlock/1.sql
internal/integration/testdata/migrations/mysqlock/2.sql
internal/integration/testdata/migrations/mysqlock/3.sql
internal/integration/testdata/migrations/mysqlock/atlas.sum

cmd/atlas: unlock advisory lock after the command finished

---

doc/md/integrations/terraform.md

doc/integration: update TF provider doc

---

doc/website/blog/2022-11-17-terraform-v040.md

doc/md: edit blog post

---

doc/website/src/css/custom.css

website: fix footer title color

---

cmd/atlas/internal/cmdapi/migrate.go
cmd/atlas/internal/cmdapi/migrate_test.go
cmd/atlas/internal/cmdlog/cmdlog.go
cmd/atlas/internal/migrate/migrate_test.go
cmd/atlas/internal/migrate/report.go
cmd/atlas/internal/migrate/report_test.go

Will add there the logging for the schema command

cmd/atlas: move migrate command logging to cmdlog

---

internal/integration/testdata/mysql/foreign-key.txt
internal/integration/testdata/postgres/foreign-key.txt
internal/integration/testdata/postgres/index-operator-class.txt
internal/integration/testdata/postgres/index-type.txt
internal/integration/testdata/postgres/index-unique-constraint.txt
sql/postgres/sqlspec.go

Also, add some MySQL sanity tests that I forgot to add in the previous PR.

sql/postgres: avoid printing the index type if it is the default

---

cmd/atlas/internal/cmdapi/schema.go
cmd/atlas/internal/cmdapi/schema_test.go
cmd/atlas/internal/cmdlog/cmdlog.go
cmd/atlas/internal/cmdlog/cmdlog_test.go
doc/md/reference.md
sql/mysql/sqlspec.go
sql/postgres/sqlspec.go
sql/sqlite/sqlspec.go

cmd/atlas: basic json logging for schema inspect

---

sql/mysql/internal/mysqlversion/mysqlversion.go
sql/mysql/internal/mysqlversion/mysqlversion_test.go

Fixed https://github.com/ariga/atlas/issues/1349

sql/mysql/mysqlversion: ignore server build info on compare

---

cmd/atlas/internal/cmdapi/migrate.go
cmd/atlas/internal/cmdapi/migrate_test.go
cmd/atlas/internal/cmdlog/cmdlog.go
cmd/atlas/internal/cmdlog/cmdlog_test.go
cmd/atlas/internal/migrate/migrate.go
cmd/atlas/internal/migrate/migrate_test.go
doc/md/reference.md
internal/integration/testdata/sqlite/cli-migrate-set.txt

Docs will be added in a separate PR. Sorry for all the redundant changes, I unindented one block that caused this.

cmd/atlas: improve 'atlas migrate set' command

---

doc/md/versioned/diff.mdx
sql/postgres/diff.go

Fixed https://github.com/ariga/atlas/issues/1407

sql/postgres: use the database to compare expressions only

---

sql/migrate/dir.go
sql/migrate/dir_test.go

sql/migrate: support reading file directives

---

internal/integration/testdata/mysql/column-default-expr.txt
sql/mysql/diff.go

Fixed https://github.com/ariga/atlas/issues/1429

sql/mysql: unquote timestamp default values on diff

---

sql/postgres/convert.go
sql/postgres/diff.go
sql/postgres/driver.go
sql/postgres/inspect.go
sql/postgres/sqlspec.go
sql/postgres/sqlspec_test.go

See: https://www.postgresql.org/docs/current/datatype-oid.html
Ref: https://github.com/ariga/atlas/issues/1428

sql/postgres: add internal and special types

---

internal/integration/testdata/postgres/column-internal.txt

Fixed https://github.com/ariga/atlas/issues/1428

internal/integration: tests postgres internal types

---

internal/integration/testdata/sqlite/index-expr.txt
sql/internal/sqlx/sqlx_test.go
sql/sqlite/inspect.go
sql/sqlite/inspect_test.go

Fixed https://github.com/ariga/atlas/issues/1436

sql/sqlite: support reading index part with expressions

---

internal/integration/testdata/sqlite/cli-inspect.txt
sql/sqlite/convert.go
sql/sqlite/sqlspec.go
sql/sqlite/sqlspec_test.go

Fixed https://github.com/ariga/atlas/issues/1448

sql/sqlite: add uint64 to sqlspec types

---

cmd/atlas/internal/lint/run.go
sql/migrate/dir.go

cmd/lint: fixed atlas.sum report on empty dir

---

sql/migrate/dir.go
sql/migrate/dir_test.go

Nothing major here, just some parts that bothered me.

sql/migrate: small refactor and test changes

---

doc/website/package-lock.json
doc/website/package.json
doc/website/src/pages/index.js

Updated with React version of landing page

doc/website: new front page design

---

cmd/atlas/x/x.go

atlas/x: ignore SilentError

---

doc/website/package-lock.json
doc/website/package.json
doc/website/src/pages/index.js

Revert "doc/website: new front page design"

---

cmd/atlas/internal/lint/run.go

atlas/lint: change Result to FileReport

---

cmd/atlas/internal/cmdext/cmdext.go

cmd/atlas: add drop column and drop index to entloader

---

internal/integration/postgres_test.go
sql/postgres/inspect.go
sql/postgres/inspect_test.go

Fixed https://github.com/ariga/atlas/issues/1520

sql/postgres: accept sequence quoted as identifiers

---

sql/migrate/lex.go
sql/migrate/testdata/lex/15_dollar_quote.sql
sql/migrate/testdata/lex/15_dollar_quote.sql.golden

sql/migrate: support dollar quoted string in scanner

---

sql/postgres/migrate.go
sql/postgres/migrate_test.go

Fixed https://github.com/ariga/atlas/issues/1551

sql/postgres: drop constraints first before adding new

---

doc/md/concepts/url.mdx
doc/website/package-lock.json
sql/mysql/driver.go
sql/mysql/driver_test.go

See: https://github.com/ariga/atlas/issues/1587

sql/mysql: support opening driver using unix sockets

---

sql/internal/sqlx/plan.go
sql/internal/sqlx/plan_test.go
sql/postgres/migrate_test.go

Fixed https://github.com/ariga/atlas/issues/1585

sql/postgres: drop foreign-keys before dropping tables

---

doc/website/package-lock.json
doc/website/package.json

Added possibility to copy code 
@a8m

add sh code

---

doc/md/getting-started/getting-started.mdx

doc: update discord link in getting-started

---

cmd/atlas/internal/cmdapi/cmdapi.go
sql/migrate/dir.go

sql/migrate: remove Validate hack

---

cmd/atlas/internal/cmdapi/migrate.go
cmd/atlas/internal/cmdapi/migrate_test.go

i.e., did not finish/exit gracefully

cmd/atlas: report migrations that were failed early

---

doc/md/cloud/directory.mdx

doc/website: add documentation about slack integration

---

cmd/atlas/internal/cmdapi/migrate.go
cmd/atlas/internal/cmdapi/migrate_test.go
cmd/atlas/internal/cmdext/cmdext.go

- atlas/cmdapi: revert fixed dir name with flash (#1698)
- atlas/cmdapi: use full path for dir name

atlas/cmdapi: use full path for directory name

---

.github/workflows/cd-docker-push-cockroach_oss.yaml
.github/workflows/cd-docker-push-mysql_oss.yaml
.github/workflows/cd-website_oss.yaml
.github/workflows/ci-dialect.yaml
.github/workflows/ci-dialect_oss.yaml
.github/workflows/ci-go.yaml
.github/workflows/ci-website_oss.yaml
internal/ci/ci.tmpl
internal/ci/main.go

This PR is the first one preparing the community edition repository for Atlas.

.github: split into oss and ent distribution

---

doc/website/package-lock.json
doc/website/package.json
doc/website/src/pages/index.js

doc/website: adding events

---

cmd/atlas/internal/cmdapi/schema_test.go

Context: https://github.com/ariga/atlas/issues/1708

cmd/atlas: add example for 'schema diff' with dev and exclude defined in config

---

cmd/atlas/internal/docker/docker.go
sql/mysql/inspect.go
sql/mysql/inspect_test.go
sql/mysql/tidb.go

`EXPLAIN` before is described here: https://github.com/ariga/atlas/issues/1727#issuecomment-1582487319
`EXPLAIN` after:
```
+----+-------------------+------------+------------+--------+------------------------+------------+---------+-----------------------+------+----------+----------------------------------------------+
| id | select_type       | table      | partitions | type   | possible_keys          | key        | key_len | ref                   | rows | filtered | Extra                                        |
+----+-------------------+------------+------------+--------+------------------------+------------+---------+-----------------------+------+----------+----------------------------------------------+
|  1 | PRIMARY           | cat        | NULL       | index  | PRIMARY …
```

sql/mysql: improve foreign-keys inspection query

---

sql/mssql/convert.go
sql/mssql/inspect.go
sql/mssql/inspect_test.go
sql/mssql/sqlspec_test.go

- sql/mssql: inspect columns and tests

sql/mssql: inspect columns and more tests

---

sql/postgres/inspect.go
sql/postgres/inspect_test.go

Fixed https://github.com/ariga/atlas/issues/1711#issuecomment-1572529934

sql/postgres: support scanning prefixed sequences

---

sql/mssql/driver.go
sql/mssql/inspect.go
sql/mssql/inspect_test.go
sql/mssql/sqlspec.go
sql/mssql/sqlspec_test.go

- sql/mssql: basic tests for sqlspec
- sql/mssql: support for index inspect and sqlspec

sql/mssql: support for index inspect and sqlspec

---

sql/mssql/inspect.go
sql/mssql/inspect_test.go

- sql/mssql: inspect checks
- sql/mssql: inspect computed column
- sql/mssql: inspect column default value

sql/mssql: inspect column default value

---

internal/integration/docker-compose.yaml
sql/mysql/tidb.go

Fixed https://github.com/ariga/atlas/issues/1791

sql/mysql: support reordering tidb changes by their deps

---

cmd/atlas/internal/cmdapi/schema_test.go
cmd/atlas/internal/cmdext/reader.go

Also add link to info section about dev-database in SQL schemas

cmd/atlas/internal: ensure dev-url is required in statereader

---

internal/integration/integration_test.go
internal/integration/postgres_test.go
sql/internal/specutil/convert.go
sql/postgres/diff.go
sql/postgres/diff_test.go
sql/postgres/inspect.go
sql/postgres/inspect_test.go
sql/postgres/migrate.go
sql/postgres/migrate_test.go
sql/postgres/sqlspec_test.go

sql/postgres: support schema comments

---

sql/internal/sqlx/diff.go
sql/postgres/driver.go

Also, add IF EXISTS to view deletion to avoid error in cascading table deletions

sql/postgres: views should be created with new schemas

---

doc/website/docusaurus.config.js
doc/website/src/css/custom.css

website: k8s webinar announcement bar

---

doc/md/cloud/bot.mdx

https://github.com/ariga/atlas/assets/57417100/06e6d257-5f38-4e70-a823-ad31a7fa7cf8

doc/md/cloud: update the images for creating-bots doc

---

internal/integration/testdata/postgres/index-nulls-distinct.txt
sql/postgres/diff.go
sql/postgres/diff_test.go
sql/postgres/driver.go
sql/postgres/inspect.go
sql/postgres/inspect_test.go
sql/postgres/migrate.go
sql/postgres/migrate_test.go
sql/postgres/sqlspec.go
sql/postgres/sqlspec_test.go

sql/postgres: support the NULLS [NOT] DISTINCT index attribute

---

doc/website/docusaurus.config.js
doc/website/plugins/utm-plugin/index.js
doc/website/plugins/utm-plugin/plugin.js

doc/website: auto add utm tags to cloud landing page

---

sql/internal/specutil/spec.go
sql/postgres/sqlspec.go
sql/postgres/sqlspec_test.go
sql/sqlspec/sqlspec.go

Resolve: https://github.com/ariga/atlas/issues/1984

sql: avoid ambiguity between resource label and qualifier

---

cmd/atlas/internal/cloudapi/client.go
cmd/atlas/internal/cloudapi/client_test.go

ref: https://github.com/vektah/gqlparser/blob/v1.3.1/gqlerror/error.go#L86

cmd/atlas: read and fmt gql errors

---

doc/md/declarative/inspect.mdx
sql/internal/sqlx/exclude.go
sql/internal/sqlx/exclude_test.go

sql/internal/sqlx: support type selectors on exclude globs

---

cmd/atlas/internal/cmdlog/cmdlog.go
cmd/atlas/internal/cmdlog/cmdlog_test.go

Fixed https://github.com/ariga/atlas/issues/1752

cmd/atlas: attach attributes to json format

---

cmd/atlas/internal/migratelint/lint.go
cmd/atlas/internal/migratelint/run.go

To be used by other internal code (ent)

cmd/atlas/internal: move devloader login to helper function

---

internal/integration/cockroach_test.go
internal/integration/postgres_test.go
sql/postgres/driver.go
sql/postgres/inspect.go
sql/postgres/inspect_test.go

Fixed https://github.com/ariga/atlas/issues/2093
Fixed https://github.com/ent/ent/issues/3750
Fixed https://github.com/mikestefanello/pagoda/issues/39

sql/postgres: remove unused collate/ctype attributes form inspection

---

doc/md/integrations/kubernetes/operator.mdx

Related Issue: #2051
Need to bump version of Operator charts before merge

doc/website: update operator v0.3.3

---

cmd/atlas/internal/cmdapi/schema_test.go
cmd/atlas/internal/cmdext/cmdext.go
cmd/atlas/internal/cmdext/cmdext_test.go

Fixed https://github.com/ariga/atlas/issues/2112

cmd/atlas/internal/cmdext: allow using data.template_dir as desired state

---

sql/postgres/migrate.go

Fix https://github.com/ariga/atlas/issues/2095

sql/postgres: fix empty enum schema

---

internal/integration/sqlite_test.go
sql/sqlite/migrate.go
sql/sqlite/migrate_test.go

sql/sqlite: ensure default expressions are wrapped

---

doc/md/concepts/url.mdx
doc/md/guides/sqlite/turso.md
sql/sqlite/driver.go

Add support for ws:// scheme for libSQL

---

sql/schema/schema.go

These changes support the timezone attribute.

sql/schema: add Attrs for TimeType

---

doc/md/guides/orms/gorm.md

Documentation for the issue mentioned in  https://github.com/ariga/atlas-provider-gorm/issues/19

doc/md: document tools.go for gorm provider

---

cmd/atlas/internal/cmdapi/cmdapi_test.go

reverting my previous changes. #2269

cmd/atlas/internal/cmdapi: revert t.TempDir for creating sqlite files

---

sql/sqlite/driver.go

Add libsql+file:// support

---

cmd/atlas/internal/docker/docker.go
doc/md/components/migrate-push-command.mdx
doc/md/concepts/dev.mdx
doc/website/blog/2023-10-17-automatic-migrations-for-sql-server.mdx

- doc: update SQL server DevURL to docker
- cmd/atlas: fixed pingURL for sqlserver

cmd/atlas: fixed pingURL for sqlserver

---

sql/internal/sqlx/diff.go
sql/postgres/diff_test.go

Fixed https://github.com/ariga/atlas/issues/2156

sql/internal/sqlx: diff realm adds new schema with all its resources

---

cmd/atlas/internal/docker/docker.go
cmd/atlas/internal/docker/docker_test.go

Support image name has `/` in its name

cmd/atlas: refactor parse dockerURL logic

---

sql/mysql/inspect.go
sql/postgres/inspect.go
sql/schema/exclude.go
sql/schema/exclude_test.go
sql/sqlite/inspect.go

This will be used in the cmd packages

sql: move exclude helpers from sql/internal to sql/schema

---

doc/md/declarative/inspect.mdx
sql/schema/exclude.go
sql/schema/exclude_test.go

Closed https://github.com/ariga/atlas/discussions/2352

sql/schema: support excluding enum objects

---

internal/integration/testdata/mysql/cli-migrate-lint-add-notnull.txt
sql/mysql/mysqlcheck/mysqlcheck.go
sql/mysql/mysqlcheck/mysqlcheck_test.go

Fixed https://github.com/ariga/atlas/issues/2364

sql/mysql/mysqlcheck: skip MY101 for auto-increment columns

---

sql/migrate/lex.go
sql/migrate/testdata/lexgroup/2_function.sql
sql/migrate/testdata/lexgroup/2_function.sql.golden

Fixed https://github.com/ariga/atlas/issues/2397

sql/migrate: fix compound blocks scanning

---

doc/md/atlas-schema/hcl.mdx

Views conflicts with other resources that are required for their existence. e.g., matviews, procs, funcs, triggers, etc.

doc: filter views for non-logged in

---

doc/md/atlas-schema/hcl-types.md

Mostly base from this page: https://learn.microsoft.com/en-us/sql/t-sql/data-types/data-types-transact-sql

doc/md: update HCL types for MSSQL

---

doc/md/concepts/url.mdx

doc/clickhouse: add urls

---

doc/md/guides/deploying/secrets.mdx

doc/deploying/secrets: add parameter store example

---

cmd/atlas/generate.go

cmd/atlas: rm gen

---

sql/internal/sqlx/plan.go
sql/internal/sqlx/plan_test.go

When table's triggers referenced to other types, it should drop first then types.

sql/sqlx: drop the table before drop UDTs

---

doc/md/atlas-schema/projects.mdx

doc: add usage details to composite_schema

---

cmd/atlas/internal/cmdlog/cmdlog.go
sql/internal/sqlx/dev.go
sql/internal/sqlx/diff.go
sql/mysql/diff.go
sql/postgres/driver_oss.go
sql/postgres/inspect.go
sql/postgres/sqlspec.go
sql/schema/dsl.go
sql/schema/schema.go
sql/sqlite/diff.go

sql/postgres: initial support for extensions

---

doc/md/concepts/url.mdx

Issue: https://github.com/ariga/atlas/issues/2590

doc/md: update document for AAD support

---

cmd/atlas/internal/cmdapi/project.go
cmd/atlas/internal/cmdapi/project_test.go

The flag below should evaluate only the first block, not both.
```
--env dev
```
```hcl
env "dev" {
...
}
env {
name = atlas.env
...
}
```

cmd/atlas: labeled envs should take precedence on non-labeled ones

---

doc/md/reference.md
doc/md/versioned/apply.mdx
doc/md/versioned/down.mdx
doc/website/sidebars.js

Blog post will come up in another PR.

doc/md: add migrate down

---

sql/postgres/inspect.go

Fixed https://github.com/ariga/atlas/issues/2677

sql/postgres: match on both pg_depend.objid add pg_depend.classid

---

doc/md/atlas-schema/hcl-types.md

doc/clickhouse: add AggregateFunction data type

---

sql/postgres/sqlspec.go
sql/postgres/sqlspec_test.go

sql/postgres: add nulls_first/last to sqlspec

---

cmd/atlas/main.go

cmd/atlas: print update notification to stderr

---

sql/mysql/convert.go
sql/mysql/diff.go
sql/mysql/driver.go
sql/mysql/inspect.go
sql/mysql/inspect_test.go
sql/mysql/sqlspec.go
sql/mysql/sqlspec_test.go

Fixed: https://github.com/ariga/atlas-provider-gorm/issues/46

sql/mysql: support inet4 + inet6 for MariaDB 10.10+

---

README.md
doc/md/atlas-schema/hcl-types.md
doc/md/atlas-schema/hcl.mdx
doc/md/atlas-schema/projects.mdx
doc/md/atlas-schema/sql.mdx
doc/md/components/card.tsx
doc/md/components/migrate-push-command.mdx
doc/md/concepts/dev.mdx
doc/md/concepts/url.mdx
doc/md/declarative/apply.mdx
doc/md/declarative/diff.mdx
doc/md/declarative/inspect.mdx
doc/md/guides/guides.mdx
doc/md/guides/redshift.mdx
doc/md/versioned/apply.mdx
doc/md/versioned/diff.mdx
doc/md/versioned/intro.mdx
doc/md/versioned/lint.mdx
doc/website/sidebars.js

Updated for Redshiftdata Urls:
Updated for guide
https://github.com/ariga/atlas/assets/16095902/379a4bf1-7378-43cd-ac75-03f6a6cc5944

doc/md: add redshift

---

doc/md/guides/orms/gorm.md

Document for the new release of Atlas GORM Provider https://github.com/ariga/atlas-provider-gorm/releases/tag/v0.4.0

doc/website: add usage document for the view feature in GORM provider

---

doc/md/integrations/circleci-orbs.mdx
doc/website/sidebars.js

https://github.com/ariga/atlas/assets/16095902/95ec3b96-b1f9-43e2-8521-e9f402fedab5

doc/website: add circleci integrations

---

doc/md/cloud/deployment.mdx

https://github.com/ariga/atlas/assets/73284641/c4dbb8c0-832a-43cf-bb63-e1657cb2cbf0

doc/md: update deployment screenshots

---

cmd/atlas/internal/cmdapi/cmdapi_oss.go
cmd/atlas/internal/cmdapi/migrate.go
cmd/atlas/internal/migratelint/run.go
cmd/atlas/internal/migratelint/run_test.go

cmd/atlas: minor changes to report non-linear errors

---

doc/md/integrations/github-actions.mdx

https://github.com/ariga/atlas/assets/16095902/5e90a572-298a-4ba1-a260-9fde3f93a603

doc/md/integration: sync github-actions doc

---

sql/postgres/diff.go
sql/postgres/driver_oss.go
sql/postgres/inspect.go
sql/postgres/inspect_test.go
sql/postgres/migrate.go
sql/postgres/sqlspec.go

sql/postgres: expose postgres policies

---

cmd/atlas/internal/cmdapi/cmdapi_oss.go
doc/md/home/docs.mdx
doc/website/docusaurus.config.js

cmd/atlas: informative message for unsupported commands

---

cmd/atlas/doc.tmpl
doc/md/guides/migration-tools/golang-migrate.md
doc/md/guides/migration-tools/goose-import.md
doc/md/reference.md
doc/website/blog/2024-07-09-v025-row-level-security.mdx
doc/website/docusaurus.config.js

Revert "doc: remove trailing slash by default"

---

doc/md/integrations/circleci-orbs.mdx

https://github.com/ariga/atlas/assets/16095902/fa2afce6-dd95-4dc1-a732-6c1ec637e523

doc/md/integrations: sync circleci-orbs doc

---

doc/md/atlas-schema/hcl.mdx

doc: skip redshift changes on sort style "AUTO"

---

sql/postgres/migrate.go
sql/postgres/migrate_test.go

Fixed https://github.com/ariga/atlas/issues/3011

sql/postgres: support renaming index with qualifiers

---

sql/postgres/convert.go
sql/postgres/driver.go
sql/postgres/sqlspec.go
sql/postgres/sqlspec_test.go

Closed https://github.com/ariga/atlas/issues/2771

sql/postgres: add xid/xid8 to builtin spec types

---

internal/integration/testdata/postgres/index-nulls-distinct.txt
sql/postgres/migrate.go
sql/postgres/migrate_test.go

Fixed https://github.com/ariga/atlas/issues/2818

sql/postgres: fix nulls not distinct usage in unique constraints

---

doc/md/guides/guides.mdx
doc/md/guides/orms/gorm.mdx
doc/md/guides/orms/gorm/getting-started.md
doc/md/guides/orms/gorm/gorm.mdx
doc/md/guides/orms/gorm/program.mdx
doc/md/guides/orms/gorm/standalone.mdx
doc/md/guides/orms/gorm/visualize.mdx
doc/md/home/components/quick-start.tsx
doc/website/sidebars.js

https://github.com/user-attachments/assets/3f2059cf-580f-4ab2-a1dd-4c13b5442e11

doc/md: add gorm docs

---

cmd/atlas/internal/cmdapi/cmdapi_oss.go
sql/sqlcheck/sqlcheck.go

sql/sqlcheck: add SuggestFix helper to Diagnostic

---

sql/mysql/driver_oss.go
sql/mysql/sqlspec.go
sql/mysql/sqlspec_test.go

sql/mysql: move views spec functions to stubs

---

doc/md/monitoring/01-home.mdx

doc/md: add drift detection card to monitoring home page doc

---

cmd/atlas/internal/cmdapi/migrate.go
cmd/atlas/internal/cmdapi/project.go
sql/migrate/migrate.go

cmd/atlas/internal/cmdapi: support env.migration.exclude attribute

---

cmd/atlas/internal/cmdext/cmdext.go
cmd/atlas/internal/cmdext/cmdext_test.go

cmd/atlas/internal/cmdext: ignore cloud block if token is not set

---

doc/website/package-lock.json
doc/website/package.json

Revert "doc/optimize-images"

---

cmd/atlas/internal/cmdapi/cmdapi_oss.go
cmd/atlas/internal/cmdapi/project.go
cmd/atlas/internal/cmdapi/schema.go

cmd/atlas/internal/cmdapi: add dry-run and format flags to schema clean

---

cmd/atlas/internal/cmdapi/cmdapi_oss.go
doc/md/cloud/features/registry.mdx
doc/md/hcldoc/config.mdx
doc/md/hcldoc/testing.mdx
doc/website/docusaurus.config.js

doc: add examples how to set up the registry block

---

doc/md/atlas-vs-others.mdx
doc/md/declarative/plan.mdx
doc/website/src/css/custom.css

doc: add examples for setting up schema push/plan gh actions

---

sql/internal/sqlx/diff.go
sql/internal/sqlx/sqlx.go

sql/internal/sqlx: support diffing view columns

---

cmd/atlas/internal/cmdapi/project.go
cmd/atlas/internal/cmdapi/project_test.go

cmd/atlas/internal/cmdapi: allow schema.src to accept list(string)

---

sql/internal/sqlx/diff.go
sql/mysql/diff.go
sql/postgres/crdb.go
sql/postgres/diff_oss.go
sql/sqlite/diff.go

sql/internal/sqlx: pass diff options to ColumnChange

---

sql/mysql/driver.go
sql/mysql/driver_test.go

Closed https://github.com/ariga/atlas/pull/2847

sql/mysql: unix connection to a specific database/schema

---

schemahcl/schemahcl.go
sql/postgres/driver.go
sql/postgres/sqlspec_oss.go
sql/postgres/sqlspec_oss_test.go

schemahcl: support passing decode-level options

---

sql/internal/specutil/convert.go
sql/mysql/sqlspec_test.go
sql/postgres/sqlspec_oss_test.go
sql/schema/dsl.go
sql/sqlite/sqlspec_test.go

sql/internal/specuti: connect columns to their indexes on eval

---

cmd/atlas/go.mod
cmd/atlas/go.sum
internal/integration/go.mod
internal/integration/go.sum

fixes https://github.com/ariga/atlas/issues/3227

go: update go-sqlite3 package

---

cmd/atlas/internal/cmdapi/cmdapi_oss.go
cmd/atlas/internal/cmdapi/project.go
cmd/atlas/internal/cmdapi/schema.go
cmd/atlas/internal/cmdext/cmdext.go
cmd/atlas/internal/cmdext/cmdext_oss.go
cmd/atlas/internal/cmdext/cmdext_test.go

cmd/atlas: remove atlas init block from oss verison

---

internal/integration/integration_test.go
internal/integration/sqlite_test.go
sql/sqlite/driver.go
sql/sqlite/driver_test.go
sql/sqlite/inspect_test.go

sql/sqlite: lock by database url

---

sql/migrate/migrate.go
sql/migrate/migrate_test.go

sql/migrate: remove partial hashes on successful apply

---

sql/internal/sqlx/sqlx.go
sql/postgres/driver.go
sql/postgres/driver_test.go

Fixed https://github.com/ariga/atlas/issues/3336

sql/postgres: restore-realm function can be called multiple times

---

sql/internal/specutil/convert.go
sql/sqlspec/sqlspec.go
sql/sqlspec/sqlspec_test.go

sql/sqlspec: allow labeling primary keys

---

schemahcl/stdlib.go
schemahcl/stdlib_test.go

schemahcl: add empty and alltrue to stdlib

---

cmd/atlas/go.mod
go.mod
internal/integration/go.mod

Addresses - https://pkg.go.dev/vuln/GO-2025-3447

all: update go version

---

cmd/atlas/internal/cmdapi/migrate_test.go
cmd/atlas/internal/cmdapi/schema_test.go
cmd/atlas/internal/migratelint/lint.go
internal/integration/mysql_test.go
internal/integration/postgres_test.go
sql/internal/sqlx/dev.go
sql/migrate/migrate.go
sql/mysql/driver_oss.go
sql/postgres/crdb_oss.go
sql/postgres/driver_oss.go
sql/sqlite/driver.go

sql/migrate: merge snapshoter/cleanchecker to driver

---

sql/internal/sqlx/plan.go

sql/internal/sqlx: skip running dependsOn if the inverse edge was already added

---

cmd/atlas/internal/cmdapi/project.go
cmd/atlas/internal/cmdapi/project_test.go

See Discord discussion: https://discord.com/channels/930720389120794674/1341161505114165258/1341443903655514163

cmd/atlas/internal/cmdapi: url scheme error should be more clear

---

cmd/atlas/internal/cmdapi/migrate.go
cmd/atlas/internal/cmdapi/schema_test.go
cmd/atlas/internal/cmdext/cmdext_oss.go
cmd/atlas/internal/cmdext/reader.go
cmd/atlas/internal/cmdlog/cmdlog.go
internal/integration/postgres_test.go
schemahcl/stdlib_test.go
sql/migrate/dir.go
sql/migrate/dir_test.go
sql/schema/migrate_test.go

sql: infra changes for support atlas:import directive

---

cmd/atlas/internal/migratelint/run.go

cmd/atlas/internal/migratelint: fix the way we count changes

---

sql/internal/sqlx/plan.go

sql/internal/sqlx: add ViewDepT option to SortChanges

---

sql/internal/specutil/spec.go
sql/internal/sqlx/plan.go

sql/internal/sqlx: row type can be view

---

sql/internal/sqlx/diff.go

Fix https://github.com/ariga/atlas/issues/3439

sql/internal/sqlx: detect ref-table change in fk constraint

---

schemahcl/schemahcl.go
schemahcl/spec.go

schemahcl: support deferring resource attribute evaluation

---

cmd/atlas/internal/cmdlog/cmdlog.go
cmd/atlas/internal/cmdlog/cmdlog_oss.go
sql/migrate/migrate.go
sql/migrate/migrate_oss.go

sql/migrate: allow mask stmts and errors

---

sql/internal/specutil/convert.go

sql/internal/specutil: postpone unfound dep search to drivers

---

schemahcl/extension.go
schemahcl/spec.go

schemahcl: add raw_expr indicator on types

---

cmd/atlas/internal/docker/docker.go
cmd/atlas/internal/docker/docker_test.go

cmd/atlas/docker: revert let Docker Engine allocate a free port

---

cmd/atlas/internal/cmdapi/cmdapi.go
cmd/atlas/internal/cmdapi/cmdapi_oss.go
cmd/atlas/internal/cmdapi/project.go
cmd/atlas/internal/cmdapi/schema.go

cmd/atlas/internal/cmdapi: allow extending apply with --include

---

cmd/atlas/internal/cmdapi/cmdapi_oss.go
cmd/atlas/internal/cmdapi/schema.go

cmd/atlas/internal/cmdapi: allow extending schema diff with --include

---

schemahcl/schemahcl.go
schemahcl/schemahcl_test.go

schemahcl: append validation error on resource error

---

sql/internal/sqlx/dev.go
sql/internal/sqlx/dev_test.go
sql/schema/dsl.go
sql/schema/schema.go

sql/schema: add PosSetter to objects
